### ISSUE TITLE
Ioda-converters YAML for the [3D]-RTMA/RRFS lgycld data

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [NOAA-EMC/RDASApp#12]
# Description
Write an example YAML for the LGYCLD [3D]-RTMA/RRFS data that converts a BUFR file to an IODA file using the _bufr2ioda.x_ for the following subsets:

NC012003 -- A61203 | M TYPE 012-003  GPS - Integrated Precipitable Water
NC012004 -- A62005 | M TYPE 012-004  Ground-based GNSS (GPS, etc.) data
**NC012150 -- A61111 | M TYPE 012-150  NASA Langley pixel-level cloud data**

- [x] Extract the BUFR table, queries, and important Mnemonics information
- [x] Use this YAML to convert into an IODA-formatted netCDF file
- [x] Ioda obs validation using _ioda-validate.x_
- [x] Perform validation for the observations using the input BUFR and output IODA file
- [ ] Add output(s) to the testoutput directory
- [ ] Add tests to the CMakeLists.txt files
- [ ] Have the tests pass

# Requirements
- All important mnemonics required by the [3D]-RTMA/RRFS users need to be known.

# Acceptance Criteria
- It will be finished when all files have been checked and tests have passed.

# Dependencies
- The _bufr2ioda.x_

**Comment by PraveenKumar-NOAA** [comment]
Performed validation of the ioda-obs in the output ioda file generated using the _bufr2ioda-x_ and following results were obtained: 

**Final results:**
  _errors:      0
  warnings:    0_

**Comment by PraveenKumar-NOAA** [comment]
Validation of the output IODA results, obtained using the lgycld ioda-converters YAML and bufr2ioda.x, for the following two observations: 

**heightOfBaseOfCloud (HOCB)**
**_BUFR plot:_** 
![bufr_lgycld_height](https://github.com/NOAA-EMC/RDASApp/assets/63739712/4073bc0d-ef55-442e-ac37-245f6182dde4)

**_IODA plot:_** 
![lgycld-ioda_height](https://github.com/NOAA-EMC/RDASApp/assets/63739712/fb02916b-682e-4cbb-b634-2c2dcdbd8f9b)

**pressureAtTopOfCloud (CDTP)**
**_BUFR plot:_** 
![bufr_lgycld_pressure](https://github.com/NOAA-EMC/RDASApp/assets/63739712/4a1f88df-c0c1-42cc-8e80-2945ac7a42ae)

**_IODA plot:_** 
![lgycld-ioda_pressure](https://github.com/NOAA-EMC/RDASApp/assets/63739712/bf5da363-08a2-45cf-8630-f91efb19fe9f)

**Comment by PraveenKumar-NOAA** [comment]
Please note extra observations into IODA plots are due to the missing observations, which are 10,764. 
Also, I used a very thinned BUFR file (from 28Mb to less than 0.5Mb) for the validation.

@MatthewMorris-NOAA please look at these plots.

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA The plots look good when compared against one another, but I'm curious why the observations are limited to the Pacific (southeast of Hawaii) and Canada & Greenland. Is this due to using a thinned BUFR file for your testing?

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA thanks, the reason for limited observations is that I used a a few observations in the plot.

**Comment by hu5970** [comment]
Could you tell me which lgycld was used for this? The data distribution does not look good to me. I would like learn more details on this convertor?

**Comment by PraveenKumar-NOAA** [comment]
@hu5970 the lgycld data file was used for the 2023060923. The plots were created for a very thinned BUFR file (reduced from 28Mb to less than 0.5Mb), hence you can not find a complete distribution here. Let me use the full data file and regenerate the plots.

**Comment by ShunLiu-NOAA** [comment]
@PraveenKumar-NOAA Could you please use RDAS test case for lgycld plot so that we may cross-check between the various observations?

**Comment by PraveenKumar-NOAA** [comment]
@hu5970 @ShunLiu-NOAA I used the RDAS test case data for 2022052700 (rap.t00z.lgycld.tm00.bufr_d) and generated the following plots for the pressure and height observations. Please let me know what you think? 

**BUFR:** 
![rrfs_bufr_lgycld_pressure](https://github.com/NOAA-EMC/RDASApp/assets/63739712/1d398bd8-b5b2-42a9-8b31-acbd21afa173)


**IODA:** 
![rrfs_lgycld-ioda_pressure](https://github.com/NOAA-EMC/RDASApp/assets/63739712/54c0fa90-61e8-4ec4-8562-e08a04ff2894)

**Comment by PraveenKumar-NOAA** [comment]
please ignore [3D]RTMA in title for these plots.

**Comment by PraveenKumar-NOAA** [comment]
**BUFR:** 
![rrfs_bufr_lgycld_height](https://github.com/NOAA-EMC/RDASApp/assets/63739712/7231c7bc-6c0b-4b2d-b3e1-a46d3ed35e4d)


**IODA:** 
![rrfs_lgycld-ioda_height](https://github.com/NOAA-EMC/RDASApp/assets/63739712/073e83f4-3fe4-49a6-b6b4-d467c5f5eb4d)

**Comment by PraveenKumar-NOAA** [comment]
@hu5970 @ShunLiu-NOAA please let me know if you are satisfied by these plots, so that I can submit a PR.

**Comment by hu5970** [comment]
@PraveenKumar-NOAA Sorry for slow response. It looks good now. Please submit PR.

**Comment by PraveenKumar-NOAA** [comment]
@hu5970 thanks for your reply. I already have a PR for this.

**Comment by PraveenKumar-NOAA** [comment]
A PR is merged for LGYCLD BUFR data, so I am closing this issue.
