### ISSUE TITLE
Update ctest for new MPAS-JEDI case

### ISSUE THREAD

**Issue by SamuelDegelia-NOAA** [NOAA-EMC/RDASApp#126]
Now that the 2024052700 case is added and well-tested, we can make plans to update the MPAS-JEDI ctest to the new case. I am opening this issue to invite further discussion on the topic. 

The directory structure is different for this new case so some edits will need to be made to `rrfs-test/CMakeLists.txt`. 

Additionally, as we add more obs types unique to RRFS, it would be helpful to keep only two ctests - one for EnVar and one for LETKF/GETKF. That way we do not add more and more ctests for each new obs type. 

Until we start using JCB, we can make use of the directory structures that @delippi created in `rrfs-test/validated_yamls`. As new obs types are added under `rrfs-test/validated_yamls/templates/obtype_config`, we can cat these together along with a header file for the specific solver. And then that newly created yaml could be used as a ctest. 

Any thoughts from others?

**Comment by guoqing-noaa** [comment]
Thanks for working on this. 
One minor comment is that we may want to change 'EnVar' to hybrid EnVar in a few months.

**Comment by SamuelDegelia-NOAA** [comment]
Good point, thanks @guoqing-noaa.

**Comment by guoqing-noaa** [comment]
Also, it will be good if we have a "bumploc" ctest if not difficult to add, :)
