### ISSUE TITLE
crtm should come from fix/ or modules, not downloaded in the clone time

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#127]
![image](https://github.com/user-attachments/assets/7c26cee0-3ab3-4e7d-a11f-83b162ebf484)

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  currently, in rdasapp, the crtm being used is from Cory's version (also for gdasapp) by setting CRTM_FIX in the module files.   But, you are right. in this situation, if we still need to clone crtm to the local dir could be discussed.

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA 
It looks like some conditions triggered the crtm downloading in my situation.  I need to double-check how this happened. Thanks!

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  I think there may have been some confusion here. The crtm lib, specifically its sources codes is needed in the building jedi  but we can module load existing crtm lib. In that case, crtm submodule is not needed . Is this what you meant?  . In addition to this, crtm data including various coefficients files are also needed.  The cloning shown in the above is for the former, which is needed.  But the crtm data should not cloned (rightly).  Did you find that cloning of crtm to sorc/crtm downloaded more than the crtm lib?

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA Normally crtm source codes only take about 55MB,  the figure I posted shows downloading data much larger than that.
My /tmp/gge directory no longer exists after Jet maintenance. I will revisit this issue when I can repeat this situation.

**Comment by guoqing-noaa** [comment]
okay, I found the reason.

There is a special `hera` code block in `build.sh`:
https://github.com/NOAA-EMC/RDASApp/blob/97afb4b98277bfe7b48fbfbc4d1026ea8de4ee22/build.sh#L147C1-L155C3
```
# JCSDA changed test data things, need to make a dummy CRTM directory
if [[ $BUILD_TARGET == 'hera' ]]; then
  if [ -d "$dir_root/bundle/fix/test-data-release/" ]; then rm -rf $dir_root/bundle/fix/test-data-release/; fi
  if [ -d "$dir_root/bundle/test-data-release/" ]; then rm -rf $dir_root/bundle/test-data-release/; fi
  mkdir -p $dir_root/bundle/fix/test-data-release/
  mkdir -p $dir_root/bundle/test-data-release/
  ln -sf $RDASAPP_TESTDATA/crtm $dir_root/bundle/fix/test-data-release/crtm
  ln -sf $RDASAPP_TESTDATA/crtm $dir_root/bundle/test-data-release/crtm
fi
```

Because I switched back and forth between hera and jet very frequently,  and I didn't expect that there would be different code logics for hera and jet. So I did not realize that it is on Jet that git clone process will download 2.5G crtm files and unzip them.

I have a PR coming soon to resolve this issue.
