### ISSUE TITLE
Ioda-converters YAML for the [3D]-RTMA/RRFS lghtng data

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [NOAA-EMC/RDASApp#13]
# Description
Write an example YAML for the LGHTNG 3[D]-RTMA/RRFS data that converts a BUFR file to an IODA file using the _bufr2ioda.x_ for the following subsets:

NC007000 | A62121 | MTYPE 007-000 SYNOPTIC FEATURES - TROPICAL STORMS
**NC007001 | A62122 | MTYPE 007-001 VAISALA LIGHTNING (NLDN SHORT-RANGE)
NC007002 | A62123 | MTYPE 007-002 VAISALA LIGHTNING (LLDN LONG-RANGE)**
NC007003 | A62125 | MTYPE 007-003 EARTH NETWORKS LIGHTNING
NC007021 | A62124 | MTYPE 007-021 BDRY LAYER HGHT FROM NEXRAD LVL 2 DECODER

- [x] Extract the BUFR table, queries, and important Mnemonics information
- [x] Use this YAML to convert into an IODA-formatted netCDF file
- [x] Ioda obs validation using _ioda-validate.x_
- [x] Perform validation for the observations using the input BUFR and output IODA file
- [ ] Add output(s) to the testoutput directory
- [ ] Add tests to the CMakeLists.txt files
- [ ] Have the tests pass

# Requirements
- All important mnemonics required by the [3D]-RTMA/RRFS users need to be known.

# Acceptance Criteria
- It will be finished when all files have been checked and tests have passed.

# Dependencies
- The _bufr2ioda.x_

**Comment by PraveenKumar-NOAA** [comment]
Performed validation of the ioda-obs in the output ioda file generated using the _bufr2ioda-x_ and following results were obtained:

**Final results:**
_errors: 0_
_warnings: 0_

**Comment by PraveenKumar-NOAA** [comment]
Validation of the output IODA results, obtained using the lghtng ioda-converters YAML and bufr2ioda.x, for the following two observations:

**lightningDischargePolarity (PLRTS)**
**_BUFR plot:_**
![bufr_lghtng_lightningDischargePolarity](https://github.com/NOAA-EMC/RDASApp/assets/63739712/0c88b6cc-1c7e-47ea-8f4a-d793eaa44e6b)


**_IODA plot:_**
![lghtng-ioda_lightningDischargePolarity (4)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/e6315bba-b689-4d18-b81f-dc6d825d1a65)



**amplitudeOfLightningStrike (AMPLS)**
**_BUFR plot:_**
![bufr_lghtng_amplitudeOfLightningStrike](https://github.com/NOAA-EMC/RDASApp/assets/63739712/85edb8fd-78c1-4330-9f57-58991551b71b)

**_IODA plot:_**
![lghtng-ioda_amplitudeOfLightningStrike (2)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/9bbace51-771c-46cb-9966-d812cd7f34ee)

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA @TingLei-NOAA please look at these validation plots, once you review them I will submit a PR.

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA The plots look good to me!

**Comment by TingLei-NOAA** [comment]
@PraveenKumar-NOAA  look good to me. but I 'd like invite @ShunLiu-NOAA to look at it.

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA look good to me. but I 'd like invite @ShunLiu-NOAA to look at it.

thanks, @ShunLiu-NOAA please look at these validation plots for LGHTNG BUFR data.

**Comment by hu5970** [comment]
@PraveenKumar-NOAA looks good to me too.

**Comment by PraveenKumar-NOAA** [comment]
A PR is merged to RDASApp for the LGHTNG YAML, hence I'm closing this issue.
