### ISSUE TITLE
FYI, `conda: command not found` when building under the EVA python environment

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#135]
```
(eva) [Jet|fe3 RDASApp]$ ./build.sh 
Building RDASApp on jet
  Build initiated Fri Aug 30 16:20:35 MDT 2024
environment: line 9: PS1: unbound variable
/apps/lmod/lmod/init/bash: line 82: conda: command not found
```

This is to document that one cannot build when the EVA Python environment is loaded.
After unloading eva, the build.sh ran successfully.

**Comment by SamuelDegelia-NOAA** [comment]
I've run into this a couple of times too. Since `build.sh` already loads the needed modules (`module load RDAS/$BUILD_TARGET.$COMPILER`), we could solve this simply by adding `module purge` to the beginning of `build.sh`.

**Comment by guoqing-noaa** [comment]
Good idea, @SamuelDegelia-NOAA! Could you create a PR for this? Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
Yep @guoqing-noaa - will do!

**Comment by guoqing-noaa** [comment]
Thanks, @SamuelDegelia-NOAA
