### ISSUE TITLE
building failure for fv3-jedi-lam for the current rdasapp

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/RDASApp#136]
Just cloned a rdasapp develop branch and git submodule update,
running build.sh show errors as :
```
RDASApp/bundle/fv3/tools/external_sst.F90(31): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [AMIP_INTERP_MOD]
use amip_interp_mod, only: i_sst, j_sst, sst_ncep, sst_anom, &
----^
/scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-emc-rdas/RDASApp/bundle/fv3/tools/external_sst.F90(31): error #6580: Name in only-list does not exist or is not accessible.   [I_SST]
use amip_interp_mod, only: i_sst, j_sst, sst_ncep, sst_anom, &
```
I am trying to use the commit of fv3-jedi-lam the same as in GDASapp.

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA I can build RDASApp on Hera:
`/scratch1/BMC/wrfruc/gge/RDASApp/build.org`

What does `fv3-jedi-lam` refer to?  Is it the same as `fv3-jedi-lm`?

I think you mean if we update all submodules to their latest commits (instead of current versions in RDASApp), the build.sh fails, right? If yes, then you are trying to use a "future" RDASApp which is not available yet, :)

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa What i experienced was after cloning the current rdasapp and running "git submodule update", the building of fv3(fv3-lam) would complain about a certain module file not available.  Even I revert the fv3 and fv3-lam to an older version (the same as the current GDASapp).  So it was sorted out it is the fms lib that is newer than the current fv3 in the current rdasapp and caused issue. So, using RDASapp's own fms submodle resolved this issue. 
That is what I had found and submitted a PR accordingly. 
That will be great if you could confirm or correct on my findings through a clean cloning and building of current RDASapp develop branch.

**Comment by TingLei-NOAA** [comment]
> @TingLei-NOAA I can build RDASApp on Hera: `/scratch1/BMC/wrfruc/gge/RDASApp/build.org`
> 
> What does `fv3-jedi-lam` refer to? Is it the same as `fv3-jedi-lm`?
> 
> I think you mean if we update all submodules to their latest commits (instead of current versions in RDASApp), the build.sh fails, right? If yes, then you are trying to use a "future" RDASApp which is not available yet, :)

And, sorry, that is a typo of mine. It should be fv3-jedi-lm:)

**Comment by TingLei-NOAA** [comment]
The issue is closed for https://github.com/NOAA-EMC/RDASApp/pull/142 would work.
