### ISSUE TITLE
Building fails for fv3jedi or mpasjedi executables on Orion

### ISSUE THREAD

**Issue by SamuelDegelia-NOAA** [NOAA-EMC/RDASApp#146]
When first running `build.sh` on Orion, the build fails when trying to build `rdas_fv3jedi.x` and `rdas_mpasjedi.x`. Restarting `build.sh` a second time allows these executables to be built successfully. I am looking into the problem.

**Comment by SamuelDegelia-NOAA** [comment]
An update here, the building failure is not due to the super executables specifically. I disabled those and the building still fails, though it does not fail all the time. And restarting the build will pick up where it left off, build a few more executables, and then crash again. Investigation is still ongoing.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA my RDASApp build failed on Orion as well.
The building log is at:
`/work/noaa/wrfruc/gge/rdas_build_test_orion/RDASApp_guoqing-noaa_reduce_copying2/log.output`

**Comment by guoqing-noaa** [comment]
FYI: But my RDASapp build and rrfs tests all succeeded on Hercules.

**Comment by SamuelDegelia-NOAA** [comment]
I have a fix that I am testing here. I think it was an issue with going over the memory limit for the login nodes on Orion. I tested decreasing the number of make jobs to 3 (`make -j3`) and it compiled successfully. I just need to see what number works while still maximizing build time. Will have a PR later today or tomorrow.

**Comment by guoqing-noaa** [comment]
Great finding!
