### ISSUE TITLE
Create an regional MPAS-JEDI Ens3DVar  case 

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/RDASApp#16]
This issue is to document the status and progress and facilitate collaborations on  creating an regional MPAS-JEDI Ens3DVar case using the MPAS forecast case created by @xyzemc 
In addition to the targeted RDAS case, it is also expected to create some automating tools to, more or less, automatically create mpas-jedi case on top of an MPAS forecast. 

Relevant sources : https://github.com/NCAR/MPAS-Workflow ; https://github.com/MPAS-Dev/MPAS-Analysis

**Comment by TingLei-NOAA** [comment]
Update on 04/04/2024:
1) A bump ensemble localization file with 1000 km horizontal length scale had been created. It was found, with 36 mpi tasks, shorter length like 200km caused the bump app be unable to finish its calculation (mostly spent on finding/creating the "subgrid" sampling  points) in a "reasonable" time window (like 8 hours).  
2) Currently,  mpas-var app would abort  for "un associated pointer" issue, which is caused from issues in the state/background variables setup.  It was found some variables are missing in the background files.

**Comment by xyzemc** [comment]
Hi Ting,    Thank you for finding the variable missing issue in the MPAS background that I generated. If you can provide some examples, it will help me to find out what other options I should try at the MPAS initialization steps.Thanks,XiaoyanOn Apr 4, 2024, at 7:23 AM, TingLei-NOAA ***@***.***> wrote:﻿
Update on 04/04/2024:

A bump ensemble localization file with 1000 km horizontal length scale had been created. It was found, with 36 mpi tasks, shorter length like 200km caused the bump app be unable to finish its calculation (mostly spent on finding/creating the "subgrid" sampling  points) in a "reasonable" time window (like 8 hours).
Currently,  mpas-var app would abort  for "un associated pointer" issue, which is caused from issues in the state/background variables setup.  It was found some variables are missing in the background files.

**Comment by TingLei-NOAA** [comment]
@xyzemc  Thanks.  I have two cdl files (from "ncdump -h")  from your case (bg.2022-05-26_19.00.00.nc.cdl )  and the mpas tutorial tests (bg.2019-05-01_00.00.00.nc.cdl) respectively in hera:/home/Ting.Lei/dr-share.
Among the missing variables, those maybe-coordinated related variables like pressure_base, theta_base would maybe be required for a mpas-jedi run.  
The complain from the mpas-jedi app about missing variables are : 
```
WARNING: Variable cldfrac not in input file.
WARNING: Variable re_cloud not in input file.
WARNING: Variable re_ice not in input file.
WARNING: Variable re_snow not in input file.
WARNING: Variable pressure_p not in input file.
WARNING: Variable pressure_base not in input file.
WARNING: Variable rho_base not in input file.
WARNING: Variable theta_base not in input file.
WARNING: Variable refl10cm_max not in input file.
WARNING: Variable lai not in input file.
WARNING: Variable sfc_albbck not in input file.
WARNING: Variable sfc_albedo not in input file.
WARNING: Variable sfc_albedo_seaice not in input file.
WARNING: Variable sfc_emibck not in input file.
WARNING: Variable mavail not in input file.
WARNING: Variable sfc_emiss not in input file.
WARNING: Variable thc not in input file.
WARNING: Variable ust not in input file.
WARNING: Variable xicem not in input file.
WARNING: Variable z0 not in input file.
WARNING: Variable znt not in input file.
WARNING: Variable snowc not in input file.
WARNING: Variable tmn not in input file.
WARNING: Variable seaice not in input file.
WARNING: Variable dzs not in input file.
WARNING: Variable zs not in input file.
WARNING: Variable ter not in input file.
WARNING: Variable h_oml_initial not in input file.
```

**Comment by xyzemc** [comment]
> @xyzemc Thanks. I have two cdl files (from "ncdump -h") from your case (bg.2022-05-26_19.00.00.nc.cdl ) and the mpas tutorial tests (bg.2019-05-01_00.00.00.nc.cdl) respectively in hera:/home/Ting.Lei/dr-share. Among the missing variables, those maybe-coordinated related variables like pressure_base, theta_base would maybe be required for a mpas-jedi run. The complain from the mpas-jedi app about missing variables are :
> 
> ```
> WARNING: Variable cldfrac not in input file.
> WARNING: Variable re_cloud not in input file.
> WARNING: Variable re_ice not in input file.
> WARNING: Variable re_snow not in input file.
> WARNING: Variable pressure_p not in input file.
> WARNING: Variable pressure_base not in input file.
> WARNING: Variable rho_base not in input file.
> WARNING: Variable theta_base not in input file.
> WARNING: Variable refl10cm_max not in input file.
> WARNING: Variable lai not in input file.
> WARNING: Variable sfc_albbck not in input file.
> WARNING: Variable sfc_albedo not in input file.
> WARNING: Variable sfc_albedo_seaice not in input file.
> WARNING: Variable sfc_emibck not in input file.
> WARNING: Variable mavail not in input file.
> WARNING: Variable sfc_emiss not in input file.
> WARNING: Variable thc not in input file.
> WARNING: Variable ust not in input file.
> WARNING: Variable xicem not in input file.
> WARNING: Variable z0 not in input file.
> WARNING: Variable znt not in input file.
> WARNING: Variable snowc not in input file.
> WARNING: Variable tmn not in input file.
> WARNING: Variable seaice not in input file.
> WARNING: Variable dzs not in input file.
> WARNING: Variable zs not in input file.
> WARNING: Variable ter not in input file.
> WARNING: Variable h_oml_initial not in input file.
> ```

Could you please link the restart file under /scratch1/NCEPDEV/fv3-cam/Xiaoyan.Zhang/mpas/regional/CONUS_15km/JEDI_MPAS_CONUS/background as the bg file for JEDI. I found those variables are in the restart files.

**Comment by TingLei-NOAA** [comment]
Following @xyzemc  suggestion ,  restart files are used now , rather than "mpasout" files, which resolved the above missing variables issues. 
A Ens3Dvar Case has been setup  to run to completion successfully,  the results look reasonable as below  (Temperature increment)
```
![image](https://github.com/NOAA-EMC/RDASApp/assets/63461756/82d63167-6e75-4318-8827-14ae09cbc200)
```
![image](https://github.com/NOAA-EMC/RDASApp/assets/63461756/82d63167-6e75-4318-8827-14ae09cbc200)
It should be noted, the observation used in this case are directly from RDAS's fv3-jedi  case and its observation session of yaml was directly pasted in the mpas-jedi yaml.  It gives me more confidence on the expected interactions among different components of JEDI ( UFO, IODA, OOPS and model interfaces ) following the "separations of concerns"  principle.

**Comment by TingLei-NOAA** [comment]
It is completed and a 3dEnvar mpas-jedi case has been added to RDAS rrfs test component.
