### ISSUE TITLE
update the mpas_2024052700 case to use the mpasout files

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#160]
@chunhuazhou has generated background and 30 member mpasout files which include `u`, `uReconstructZonal`, `uReconstructMeridional` variables.

A PR will be created soon to update the mpas_2024052700 case to use these mapsout files.

Hope this helps the further investigation of issue https://github.com/NOAA-EMC/RDASApp/issues/148

**Comment by guoqing-noaa** [comment]
For reference, this is the ensemble spread at level=23:
![image](https://github.com/user-attachments/assets/f006ffd5-b836-4175-bdae-c029555e9be2)

**Comment by guoqing-noaa** [comment]
Here are the analysis increments from a single observation test:
![image](https://github.com/user-attachments/assets/8d23b937-dd39-4e07-a50b-0bc8474d4eb6)

**Comment by guoqing-noaa** [comment]
Here are the analysis increment from the bumploc files generated from the mpasout files:
The max value is changed from 1.68 to 1.64 and there are small pattern changes as well when you zoom in.

![image](https://github.com/user-attachments/assets/e6120356-5d41-484c-a847-8b2e5fad9ce7)

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA @TingLei-NOAA  If you want to take a close examination of the two sets of bumploc files, they are at:
`/mnt/lfs5/BMC/wrfruc/gge/RDASApp/expr/mpas_2024052700/data/bumploc`  

Thanks!

**Comment by chunhuazhou** [comment]
@guoqing-noaa The small difference might be from the model change to tag v8.2.1, which I used for the mpasout/mpasin testing previously.

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa The small difference might be from the model change to tag v8.2.1, which I used for the mpasout/mpasin testing previously.

The differenences between the above two analysis increment fields only come from using different bumploc files (the bkg and ensembles are the same)
@TingLei-NOAA @SamuelDegelia-NOAA Does the bump localization depend on the model meteorological fields? Correct me if I am wrong, but I had an impression that they are invariant with changed meteorological fields.

**Comment by SamuelDegelia-NOAA** [comment]
> @TingLei-NOAA @SamuelDegelia-NOAA Does the bump localization depend on the model meteorological fields? Correct me if I am wrong, but I had an impression that they are invariant with changed meteorological fields.

@guoqing-noaa Correct, the bump localization files should not depend on the meteorological fields. I just confirmed by running bump using different ensemble members as the background, and the bumploc files were the same each time.

**Comment by guoqing-noaa** [comment]
Link issue #89 where we have spread and increments plots using the restart files

**Comment by delippi** [comment]
I also noticed some strange things happening in the southern part of the domain. Here is the ensemble spread but with the colorbar zoomed in near zero. You can see a similar pattern in @guoqing-noaa's first plot as well. I believe this might be why I was having trouble assimilating obs over that region. I just use the offline domain check to remove obs in that location for now.

Edit: @SamuelDegelia-NOAA @ShunLiu-NOAA, I zoomed out to plot the edges better. I think this might just be an issue with map projection? I think the edges (east, west, and south) are supposed to be concave? I've tried some other projection options and haven't got things to plot nicely yet.

![spread_airTemperature](https://github.com/user-attachments/assets/09199544-cbbd-4193-b9c9-aee1ae8f062b)
