### ISSUE TITLE
Clean up build options

### ISSUE THREAD

**Issue by SamuelDegelia-NOAA** [NOAA-EMC/RDASApp#164]
Suggestions from @guoqing-noaa 

1. Remove -t  target to build for <target>" as we detect machine_id automatically and don't need this parameter any more.

2. Do we have situations where we only want to build partially for only the following directories?
fv3-jedi mpas-jedi iodaconv
If we don't need this, we may safely remove the -s  only build a subset of the bundle option

3. Add an option -j number_of_processes for building so that users can specify how many processes easily at the command line, such as build.sh -j8 on Hera/Jet/hercules and build.sh -j4 on Orion.

4. We may want to make the rrfs(mpas) test as a mandate since this is a rrfs(mpas) system and every new PRs should pass all rrfs(mpas) tests. Also, we now don't copy binary data but link them instead, so the extra cost should be negligible. If we agree with this, we can remove the ADD_RRFS_TESTS variable and always add rrfs tests.

After some discussion, we would like to keep the `-s` build option, but the other suggestions here can be implemented in a PR very soon.

**Comment by guoqing-noaa** [comment]
Thanks, @SamuelDegelia-NOAA.
It make senses to keep the `-s` option at the moment.

Just curious, how long does it take to build the mega executable? If it take some minutes, do we want to add an option to switch it on and off?

**Comment by SamuelDegelia-NOAA** [comment]
It takes an extra 2.5 min total to build both of the mega executables. I think that is borderline to when we would want to turn them off. But I think adding the option is still a good idea since there is really no reason to build them until we start cycling.
