### ISSUE TITLE
MPAS plot scripts plot incorrect domain shapes

### ISSUE THREAD

**Issue by delippi** [NOAA-EMC/RDASApp#173]
The plotting scripts used for visualizing data on an MPAS grid is producing incorrect plots due to issues with handling concave boundaries. The scripts are intended to create contour plots for temperature increments, spread, etc., but the visual output is distorted around the concave areas of the domain.

For example, here is the ensemble spread plot with lat/lon points overlaid. The scatter points (blue) show what the domain should look like while the contour fill is trying to fill in areas that are not actually part of the domain. This can lead to confusion when interpreting plots.
![spread_airTemperature](https://github.com/user-attachments/assets/c59d95a4-69f9-4f51-8841-6eaa8c2a86ff)

This issue will track progress with updating the plotting scripts.

**Comment by delippi** [comment]
I'm able to get the plot to show the correct domain shape by using:
```
# Plot using Delaunay triangulation
triang = Triangulation(lons, lats, tri.simplices)
mask = TriAnalyzer(triang).get_flat_tri_mask(min_circle_ratio=0.1)
triang.set_mask(mask)

# Plot the variance data on the triangulation
c1 = m1.tricontourf(triang, var, cmap=cmap, levels=100, transform=ccrs.PlateCarree())
```

Left is before. Right is after.
![merged_image](https://github.com/user-attachments/assets/65e7884b-003b-4be4-8382-2825c0812045)

**Comment by guoqing-noaa** [comment]
Great work. Thanks, @delippi!

**Comment by delippi** [comment]
And working for the increment plot as well.

Edit: Image updated

![merged_increment_airTemperature](https://github.com/user-attachments/assets/ac3d05b5-dee4-4d7b-8f92-08ad107a6895)

**Comment by delippi** [comment]
I just used scatter(lon,lat) for plotting domain area of offline domain check. We also see why 10% hull shrink is required to remove all obs that could be outside the domain (especially in the south part of the domain).
![merged_domain_check_MPAS_aircraft](https://github.com/user-attachments/assets/bb75a4cb-e406-425b-932e-7a1ffaccf28b)

**Comment by SamuelDegelia-NOAA** [comment]
Thanks @delippi this is a good find. BTW, one of my versions of the offline domain check uses a concave hull approach. That could help remove any obs inside the concave section without needing to shrink it further and remove valid obs. But that code has a problem of needing python modules that are not available with any of the RDASApp modulefiles

**Comment by delippi** [comment]
@SamuelDegelia-NOAA, It would be nice to be able to use the concave hull option. As you know, I purposefully did not because that required the additional python module and I wanted to use only what was currently available. We should talk to @CoryMartin-NOAA about what we might need to have additional python modules installed. But at the same time, the offline domain check is only supposed to be a temporary solution. However, the online domain check doesn't really work because you can't drop the obs from memory and then it gets caught up in other QC filters especially the ObsErrorFactorPressureCheck (ob error inflation). Not sure about progress on the online domain checks. I think since the offline check is only temporary it is probably fine as is. If for some reason we need to use the offline check as a more long term solution then we should consider adding those python modules.

**Comment by SamuelDegelia-NOAA** [comment]
Yeah I agree with that. For the time being I think the simpler (and faster) domain check is a good option. But if we get to the point of cycling tests (further than just the prototype phase) and the online checks are still not working, then maybe we can revisit and think about adding the concave hull approach.
