### ISSUE TITLE
Create a 66 vertical level mpasjedi case

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#176]
We will need a more realistic vertical-level configuration to facilitate the testing of surface data assimilation (especially T2m).

@chunhuazhou is working with GSL model experts to generate an MPAS configuration with 66 levels and GSL physics.
The 66 levels are to mimic the current vertical configuration in fv3-based rrfs.v1.

**Comment by guoqing-noaa** [comment]
For reference, here is the 66-vertical-level setting:

0
19
39
61
89
119
153
191
235
283
339
401
471
549
637
735
845
969
1105
1259
1427
1615
1823
2049
2301
2571
2873
3193
3547
3923
4331
4763
5221
5705
6215
6751
7313
7899
8501
9125
9755
10407
11063
11727
12401
13095
13803
14535
15279
16045
16821
17621
18435
19283
20171
21126
22133
23199
24348
25616
27034
28654
30556
32919
36165
41275

**Comment by hu5970** [comment]
@guoqing-noaa Please update those levels.

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa Please update those levels.

Updated. Thanks!

**Comment by chunhuazhou** [comment]
Closing this issue as a new issue has been created for a new vertical configuration at https://github.com/NOAA-EMC/RDASApp/issues/211
