### ISSUE TITLE
Test AMSUA in MPAS_JEDI with 12km CONUS case

### ISSUE THREAD

**Issue by xyzemc** [NOAA-EMC/RDASApp#180]
Test amsua  radiance data from noaa_19, metop_b/c, work will include the following steps:

1. convert budr data to ioda with bufr2ioda tools
2. convert bias file to ioda with bufr2ioda tools
3. copy the yaml file from GDASApp and modify it with MPAS configuration
4. check the assimilation results
5. ctest

amsua_n19 ioda data from bufr:
![image](https://github.com/user-attachments/assets/35a7d372-a72d-4e15-98ab-ed8da9b9c8df)

amsua_n19 data kept in MPAS 12km domain:
![image](https://github.com/user-attachments/assets/9fc432c3-3886-47ea-91e1-64833b2d9162)

amsua_n19 hofx value:
![image](https://github.com/user-attachments/assets/aa1475c7-dc0c-4ce1-99ec-863d995490aa)

amsua_n19 o-b:
![image](https://github.com/user-attachments/assets/d5a10b9d-31c4-4dd1-9362-7a3098326abf)

**Comment by xyzemc** [comment]
Tested the [offline domain check tools ](https://github.com/NOAA-EMC/RDASApp/pull/153)to remove the observation outside of the domain:
![image](https://github.com/user-attachments/assets/416c3590-ed65-4bc7-938c-2a58d7fd4f1f)

After offline domain check, the ioda data amsua_n19 channel 1 
![image](https://github.com/user-attachments/assets/55a74233-4de5-4f09-aa40-5002ddcc030d)

O-B channel 1 before QC:
![image](https://github.com/user-attachments/assets/a6eab848-f41d-48db-b00f-357ef5b14b7c)

O-B channel 1 after QC, nnly 26 out of 450 data assimilated after QC because channel 1 is  sensitive to the surface
![image](https://github.com/user-attachments/assets/21b59ad0-5804-4932-b9fa-b86ef49d6ff6)

For higher peaking channel 8, more data passed QC, and has smaller O-B value
![image](https://github.com/user-attachments/assets/94de511f-7c3d-424c-8236-7eff20665e3b)

**Comment by xyzemc** [comment]
Analysis increment from lower level:
![image](https://github.com/user-attachments/assets/20c64e1f-0fc4-482a-bbb2-57719e88de7b)

Analysis increment from middle level:
![image](https://github.com/user-attachments/assets/fe5f0ddc-24a8-49e1-8fa4-29b5464d199c)

**Comment by xyzemc** [comment]
The ctest result for cat the amsua_n19 yaml file to rrfs_mpasjedi_2024052700_Ens3Dvar.yaml

> ctest -R rrfs_mpasjedi_2024052700_Ens3Dvar
Test project /scratch2/NCEPDEV/fv3-cam/Xiaoyan.Zhang/noscrub/JEDI/RDASApp_09272024/build/rrfs-test
    Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar

> 1/1 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar ...   Passed  113.63 sec
> 
> 100% tests passed, 0 tests failed out of 1
> 
> Label Time Summary:
> mpi            = 113.63 sec*proc (1 test)
> rdas-bundle    = 113.63 sec*proc (1 test)
> script         = 113.63 sec*proc (1 test)
> 
> Total Test time (real) = 114.83 sec
>

**Comment by guoqing-noaa** [comment]
> The ctest result for cat the amsua_n19 yaml file to rrfs_mpasjedi_2024052700_Ens3Dvar.yaml
> 
> > ctest -R rrfs_mpasjedi_2024052700_Ens3Dvar
> > Test project /scratch2/NCEPDEV/fv3-cam/Xiaoyan.Zhang/noscrub/JEDI/RDASApp_09272024/build/rrfs-test
> > Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar
> 
> > 1/1 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar ...   Passed  113.63 sec
> > 100% tests passed, 0 tests failed out of 1
> > Label Time Summary:
> > mpi            = 113.63 sec_proc (1 test)
> > rdas-bundle    = 113.63 sec_proc (1 test)
> > script         = 113.63 sec*proc (1 test)
> > Total Test time (real) = 114.83 sec

@xyzemc My understanding is that you added the amsua_n19 observation to the minimization process, right? If so, did you update the reference files?  If not, we would expect the ctest to  fail.

**Comment by xyzemc** [comment]
> > The ctest result for cat the amsua_n19 yaml file to rrfs_mpasjedi_2024052700_Ens3Dvar.yaml
> > > ctest -R rrfs_mpasjedi_2024052700_Ens3Dvar
> > > Test project /scratch2/NCEPDEV/fv3-cam/Xiaoyan.Zhang/noscrub/JEDI/RDASApp_09272024/build/rrfs-test
> > > Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar
> > 
> > 
> > > 1/1 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar ...   Passed  113.63 sec
> > > 100% tests passed, 0 tests failed out of 1
> > > Label Time Summary:
> > > mpi            = 113.63 sec_proc (1 test)
> > > rdas-bundle    = 113.63 sec_proc (1 test)
> > > script         = 113.63 sec*proc (1 test)
> > > Total Test time (real) = 114.83 sec
> 
> @xyzemc My understanding is that you added the amsua_n19 observation to the minimization process, right? If so, did you update the reference files? If not, we would expect the ctest to fail.

Yes, I add the amsua_n19 ioda data to the minimization. I did not update the reference file and the ctest failed. So this passed result is from no reference file included in the yaml file.

**Comment by guoqing-noaa** [comment]
Thanks for the clarification, @xyzemc

**Comment by xyzemc** [comment]
> Thanks for the clarification, @xyzemc

After I update the reference file with rrfs-mpasjedi-ens3dvar.out from the above ctest, and included in the yaml file. The new ctest passed as:

> ctest -R rrfs_mpasjedi_2024052700_Ens3Dvar
Test project /scratch2/NCEPDEV/fv3-cam/Xiaoyan.Zhang/noscrub/JEDI/RDASApp_09272024/build/rrfs-test
    Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar
1/1 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar ...   Passed  122.34 sec

> 100% tests passed, 0 tests failed out of 1
> 
> Label Time Summary:
> mpi            = 122.34 sec*proc (1 test)
> rdas-bundle    = 122.34 sec*proc (1 test)
> script         = 122.34 sec*proc (1 test)
> 
> Total Test time (real) = 123.18 sec
