### ISSUE TITLE
building error on Orion

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [NOAA-EMC/RDASApp#19]
When I build RDASApp on Orion, I got the error message below:

-- Adding bundle project ioda-data
CMake Error at /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env/install/intel/2022.0.2/ecbuild-3.7.2-3n22kc3/share/ecbuild/cmake/ecbuild_log.cmake:190 (message):
  CRITICAL - Source directory
  '/work/noaa/da/Shun.Liu/noscrub/JEDI/RDASApp/bundle/ioda-data' for
  subproject 'ioda-data' does not exist or does not contain a CMakeLists.txt
  file.
Call Stack (most recent call first):
  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env/install/intel/2022.0.2/ecbuild-3.7.2-3n22kc3/share/ecbuild/cmake/ecbuild_bundle.cmake:166 (ecbuild_critical)
  CMakeLists.txt:115 (ecbuild_bundle)

It appears the directory below is not available in Cory's account anymore. 
lrwxrwxrwx 1 sliu da   54 Apr  2 11:18 ioda-data -> /work2/noaa/da/cmartin/CI/RDASApp/data/jcsda/ioda-data

**Comment by CoryMartin-NOAA** [comment]
@ShunLiu-NOAA thanks, I'll fix this later today

**Comment by CoryMartin-NOAA** [comment]
If you build without `-d` flag in the build script it should at least compile.

**Comment by ShunLiu-NOAA** [comment]
Thanks. I completes "build" without "-d" on Orion.

**Comment by CoryMartin-NOAA** [comment]
Please @ShunLiu-NOAA or someone else try and see if this issue is resolved now. Thanks!

**Comment by ShunLiu-NOAA** [comment]
Tested on Orion. The issue is resolved. Thanks.
