### ISSUE TITLE
update RDASApp submodules to match mpasjedi-v3.0.1 

### ISSUE THREAD

**Issue by Junjun-NOAA** [NOAA-EMC/RDASApp#193]
List of submodule changes.  PR #194 
```
ioda             c7b8760f -> d49ed17e
ufo              92ccfb2a -> 94d50d64
oops             35820130 -> d77217323
vader            e3457cba -> 6d56a1eb5
mpas             3ecd59e2 -> 41e9a3fb8   #  repo URL also changed
mpas-jedi        a1c60997 -> b9d596d7c
#fv3-jedi         d3c800b8 -> c99519638
#fv3-jedi-lm      a6e97d76 -> 30ef7a390
```

I have updated all related submodules to match mpasjedi-v3.0.1.
My fork is at https://github.com/Junjun-NOAA/RDASApp/tree/mpasjedi3.0.1.

The compilation is successful on Jet. I will do the following tests step by step:
(1) the mpas2024052700 case
(2) rrfs-tests
(3) mpas-tests
(4) fv3-tests
(5) all jedi tests

When I have more information, I will update here.

**Comment by guoqing-noaa** [comment]
To update:

The En3DVAR mpas2024052700 case succeeded by using the L55 mpasout case data from @chunhuazhou (details in PR #161).  Fix data was updated as well. Check the commits here:
https://github.com/Junjun-NOAA/RDASApp/commits/mpasjedi3.0.1/

@SamuelDegelia-NOAA In order to pass the rrfs-tests, we will need to update the reference files, could you help with Junjun on this? Thanks!

**Comment by hu5970** [comment]
@Junjun-NOAA Thanks for working on this syncing task. Did you check FV3 related submodules?

**Comment by hu5970** [comment]
@hongli-wang Could you check those submodules to see if there are the same as your test on Hera?

**Comment by Junjun-NOAA** [comment]
@hu5970 I only check out mpas-bundle. The submodules that are upgraded include: oops, ioda, ufo, vader, mpas, mpas-jedi. saber is already the latest version in current RDASApp. The crtm is not upgraded in this upgrade. Thanks!

**Comment by hu5970** [comment]
@Junjun-NOAA You will run FV3 test without updating the FV3 related submodules. When you compile the updated RDASApp, did you turn on the FV3 JEDI?

**Comment by Junjun-NOAA** [comment]
@hu5970 Yes, FV3 JEDI is turned on when compiling.

**Comment by hongli-wang** [comment]
> @hongli-wang Could you check those submodules to see if there are the same as your test on Hera?

I only updated mpas-jedi and mpas in my local RDASapp. 
Regarding mpas-jedi, my update is to Oct 8, which is just one commitment advanced to Junjun's that was updated to Sep 29. 

MPAS model is same to Junjun's with the last updated on Sep 20 by Michael Duda. 

Thanks for Junjun updating most of the submodules! I will check out hers to test radiance DA next week.

**Comment by Junjun-NOAA** [comment]
The following list the submodules I have updated with hash change included:
ioda  c7b8760fc -> d49ed17e
ufo 92ccfb2a -> 94d50d64d
oops 35820130 -> d77217323
vader e3457cba4 -> 6d56a1eb5b
mpas 3ecd59e2c -> 41e9a3fb8
    &emsp;**NOTE: the MPAS repository URL is also changed**
mpas-jedi a1c609973 -> b9d596d7c9
fv3-jedi d3c800b82 -> c995196384 
Fv3-jedi-lm a6e97d76ed -> 30ef7a3900

**Comment by guoqing-noaa** [comment]
The following **fix files** were added per the need of the submodule update and corresponding links under fix/ were updated.
```
fv3-jedi-data_2085be5_20241008
ioda-data_20241011
mpas-jedi-data/testinput_tier_1/obs
VEGPARM.TBL.20241011
NoahmpTable.TBL
```
Fix file changes were sync'ed on Jet/Hera/Orion/Hercules and archived to HPSS

`crtm/fix_REL-3.1.1.2` was added/sync'd under `RDAS_DATA` for facilitate offline mpasjedi ctests (i.e. test mpasjedi using the CRTMv3 source code but we don't update the crtm submodule in current RDASApp until everyone (especially @xyzemc and @HaidaoLin-NOAA) is ready for CRTMv3.

**Comment by SamuelDegelia-NOAA** [comment]
Hi all, looks like there is a lot of active development here. I just wanted to check if these updates include OOPS being upgraded to the latest development hash? Or does the mpasjedi version we are trying to match use a slightly older version? 

I ask because of #189 where the latest OOPS version allows use to the 'reduce obs space' filter action that greatly speeds up the GETKF. 

I would check the hashes listed by @Junjun-NOAA but I only have access to my phone right now and can't figure out how to see different commits.

**Comment by guoqing-noaa** [comment]
> Hi all, looks like there is a lot of active development here. I just wanted to check if these updates include OOPS being upgraded to the latest development hash? Or does the mpasjedi version we are trying to match use a slightly older version?
> 
> I ask because of #189 where the latest OOPS version allows use to the 'reduce obs space' filter action that greatly speeds up the GETKF.
> 
> I would check the hashes listed by @Junjun-NOAA but I only have access to my phone right now and can't figure out how to see different commits.

Unfortunately, no.  The PR you mentioned is too new  and mpasjedi.v3.0.1 did not include that PR. I commented at your issue #189.
