### ISSUE TITLE
What's this? `[NOAA-EMC/RDASApp] PR run failed: Unit Tests`

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#195]
Recently, each time we made a commit to our own fork, we would get an email notifying that `[NOAA-EMC/RDASApp] PR run failed: Unit Tests` and the Github webpage showed:
![image](https://github.com/user-attachments/assets/7ef65088-bb43-4ad2-b9df-bdf4b5d33823)

Did we recently turn on the `Unit Tests`? 

If yes, could we make it work correctly? 
If not, could we turn it off until it can work correctly?
Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
This is probably related to https://github.com/NOAA-EMC/GDASApp/pull/1332

We have a couple of github actions in place for automated testing. It looks like they are checking for pycodestyle and then running a 3dvar test. But I am not sure why they always complete so fast. It seems that RDASApp isn't actually getting built? 

See the unit test workflow here: https://github.com/NOAA-EMC/RDASApp/blob/develop/.github/workflows/unittests.yaml and an example run here:  https://github.com/NOAA-EMC/RDASApp/actions/runs/10966022592/job/30453068901 

Anyways, to fix the error here, we can follow @CoryMartin-NOAA's PR by changing `ubuntu-latest` to `ubuntu-22.04`.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Could you go ahead to fix the error?  Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
Sure, will do!

**Comment by guoqing-noaa** [comment]
This was solved. Thanks, @SamuelDegelia-NOAA
