### ISSUE TITLE
two ombg in the basic yaml configure files under rrfs-test/validated_yamls/templates/basic_config/

### ISSUE THREAD

**Issue by HaidaoLin-NOAA** [NOAA-EMC/RDASApp#229]
For the basic yaml configure files under rrfs-test/validated_yamls/templates/basic_config/, such as this one: https://github.com/NOAA-EMC/RDASApp/blob/develop/rrfs-test/validated_yamls/templates/basic_config/mpasjedi_en3dvar.yaml.
There are two ombg there, would need to rename them to make them to be different variables in the hofx files.  Otherwise, we would only get one ombg from the hofx files, in this case, it would be ombg after the first outer loop (not the original O-B).  I would like to suggest to rename the first ombg to be omgb0  (O-B) and the second ombg to be omgb1 (O-B after the first outer loop).  Other option is to remove the second ombg, only keep the first ombg if we don't want to output the O-B after the first outer loop.   This also applies to other yaml files under /basic_config/.  I will need to check more but this is my current understanding.   

iterations:
  - geometry:
      nml_file: ./namelist.atmosphere
      streams_file: ./streams.atmosphere
      deallocate non-da fields: true
      interpolation type: unstructured
    gradient norm reduction: 1e-3
    diagnostics:
      departures: ombg
    ninner: 50
  - geometry:
      nml_file: ./namelist.atmosphere
      streams_file: ./streams.atmosphere
      deallocate non-da fields: true
      interpolation type: unstructured
    gradient norm reduction: 1e-3
    diagnostics:
      departures: ombg
    ninner: 50

**Comment by guoqing-noaa** [comment]
@HaidaoLin-NOAA Do you have a run directory so that we can take a look? Thanks!

**Comment by HaidaoLin-NOAA** [comment]
@guoqing-noaa This is my jedi run path: /scratch1/BMC/wrfruc/hlin/RRFSv2/RDASApp_Junjun_jedi_3.0.1/expr/mpas_2024052700/
this is the original hofx file (using two ombg based on the basic en3dvar yaml file): rass_atms_obs_2024052700_original.nc4 
This is the new hofx file after changing the first ombg to ombg0, the second ombg to ombg1: rass_atms_obs_2024052700_ombg0_ombg1.  Please let me know if you need more information. Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
@HaidaoLin-NOAA We actually have a PR in review to fix the duplicate `ombg` occurrence in these yamls (#228). Removing the extra `ombg` did not change any of the results and the `ombg` written out the the hofx files was still the same. 

In `oops/src/oops/assimilation/CostJo.h`, it looks like the `ombg` and `oman` diagnostics are [hardcoded](https://github.com/JCSDA-internal/oops/blob/463e67a58b0f7a966bed438ea08533db9d795b3d/src/oops/assimilation/CostJo.h#L211-L218) to always be written out first the first and final outer loops. So it seems like our adding these diagnostics actually isn't even necessary. But if we wanted to output the diagnostics between outer loops, we could do like you suggest and add `ombg0` and `ombg1`. That is my understanding at least, but I am just looking at this code for the first time.

**Comment by HaidaoLin-NOAA** [comment]
@SamuelDegelia-NOAA Thank you for the information and the PR link!  Sorry, I did not know this PR and it's good to know that this PR fix this problem.  From my test, it looks like if we have the same two ombg there (in the original yaml files), then the ombg in the hofx file would be the one after the first outer loop (i.e., ombg1, if we have both ombg1 and ombg0 in the yaml file).  But I will double check this.  I think it would be good to output the diagnostics between outer loops.  Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
@HaidaoLin-NOAA It would be good to know if the ombg we use in our current systems is actually the omb or if it is the omb after the first outer loop. Thank you!

**Comment by HaidaoLin-NOAA** [comment]
@SamuelDegelia-NOAA What do you mean our current systems? with or without the this PR [https://github.com/NOAA-EMC/RDASApp/pull/228](https://github.com/NOAA-EMC/RDASApp/pull/228 )?  This is my current understanding: if with this PR, then the ombg is actually the omb, if without this PR, the ombg is omb after the first outer loop.  Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
@HaidaoLin-NOAA Sorry for the confusion. From my tests last night, PR #228 did not change any of the hofx files (including the `ombg` variable) output from our Ens3Dvar ctest. The PR was only meant to remove the duplicate `departures: ` line to avoid any confusion. But it sounds like you are saying that this might not be true and that our old yaml was actually outputting ombg from after the first outer loop. 

My question in the previous message just wanted to confirm that the two lines in our new yamls [here](https://github.com/NOAA-EMC/RDASApp/blob/effb0a7e7bab987b4da75290423d76c520fef9e7/rrfs-test/testinput/rrfs_mpasjedi_2024052700_Ens3Dvar.yaml#L19-L20) (after PR #228) are outputting the actual omb and not the omb after the first outer loop? It sounds like this is the case and that we should be good now.

**Comment by HaidaoLin-NOAA** [comment]
@SamuelDegelia-NOAA Yes, after the PR [](url)https://github.com/NOAA-EMC/RDASApp/pull/228, the two lines in our new yamls are outputtting the actual omb and not the omb after the first outer loop.  Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
Thanks for confirming @HaidaoLin-NOAA!
