### ISSUE TITLE
Trouble properly running the RRFS CTest

### ISSUE THREAD

**Issue by keenaneure** [NOAA-EMC/RDASApp#252]
> **NOTE:** To use this template, remove any sections or lines that are not needed, and delete this line before submitting your PR.

I am having trouble running the RRFS CTest, or step 3 of build_and_test.md. The first (of 8) ctests works fine, but the second one (and on) take a long time (>1 h) and still fail. This is a clone as of 12 December (today) and I am using Hera to do this.

Here is my output at the command line:
` ush/run_rrfs_tests.sh wrfruc

Currently Loaded Modules:
  1) intel/2022.1.2                   20) netcdf-fortran/4.6.1    39) openblas/0.3.24   58) libxaw/1.0.13          77) py-packaging/23.1
  2) stack-intel/2021.5.0             21) antlr/2.7.7             40) eckit/1.24.5      59) udunits/2.2.28         78) py-bottleneck/1.3.7
  3) impi/2022.1.2                    22) gsl/2.7.1               41) fftw/3.3.10       60) ncview/2.1.9           79) py-numexpr/2.8.4
  4) stack-intel-oneapi-mpi/2021.5.1  23) nco/5.0.6               42) fckit/0.11.0      61) netcdf-cxx4/4.3.1      80) py-et-xmlfile/1.0.1
  5) cmake/3.23.1                     24) parallelio/2.5.10       43) fiat/1.2.0        62) json/3.10.5            81) py-openpyxl/3.1.2
  6) gettext/0.19.8.1                 25) wget/1.14               44) ectrans/1.2.0     63) rocoto/1.3.6           82) py-six/1.16.0
  7) pcre2/10.42                      26) libxcrypt/4.4.35        45) qhull/2020.2      64) bacio/2.4.1            83) py-python-dateutil/2.8.2
  8) nghttp2/1.57.0                   27) sqlite/3.43.2           46) atlas/0.35.1      65) w3emc/2.10.0           84) py-pytz/2023.3
  9) curl/8.4.0                       28) util-linux-uuid/2.38.1  47) sp/2.5.0          66) prod_util/2.1.1        85) py-pyxlsb/1.0.10
 10) zlib/1.2.13                      29) python/3.10.13          48) gsl-lite/0.37.0   67) fms/2023.04            86) py-xlrd/2.0.1
 11) git/2.18.0                       30) boost/1.83.0            49) libjpeg/2.1.0     68) py-markupsafe/2.1.3    87) py-xlsxwriter/3.1.7
 12) pkg-config/0.27.1                31) py-setuptools/63.4.3    50) krb5/1.20.1       69) py-jinja2/3.0.3        88) py-xlwt/1.3.0
 13) hdf5/1.14.0                      32) py-numpy/1.22.3         51) libtirpc/1.3.3    70) py-cftime/1.0.3.4      89) py-pandas/1.5.3
 14) parallel-netcdf/1.12.2           33) bufr/12.0.1             52) hdf/4.2.15        71) py-netcdf4/1.5.8       90) py-xarray/2023.7.0
 15) snappy/1.1.10                    34) git-lfs/2.10.0          53) jedi-cmake/1.4.0  72) py-pybind11/2.11.0     91) RDAS/hera.intel
 16) zstd/1.5.2                       35) ecbuild/3.7.2           54) libpng/1.6.37     73) py-pycodestyle/2.11.0
 17) c-blosc/1.21.5                   36) openjpeg/2.3.1          55) libxt/1.1.5       74) libyaml/0.2.5
 18) netcdf-c/4.9.2                   37) eccodes/2.32.0          56) libxmu/1.1.4      75) py-pyyaml/6.0
 19) nccmp/1.9.0.1                    38) eigen/3.4.0             57) libxpm/4.11.0     76) py-scipy/1.11.3

+ cd /scratch1/BMC/wrfruc/eure/RDASApp/ush/../build/rrfs-test
+ pwd
/scratch1/BMC/wrfruc/eure/RDASApp/build/rrfs-test
+ ctest -j8
Test project /scratch1/BMC/wrfruc/eure/RDASApp/build/rrfs-test
    Start 2: rrfs_fv3jedi_2024052700_getkf_observer
    Start 5: rrfs_mpasjedi_2024052700_getkf_observer
    Start 1: rrfs_fv3jedi_2024052700_Ens3Dvar
    Start 4: rrfs_mpasjedi_2024052700_Ens3Dvar
    Start 7: rrfs_mpasjedi_2024052700_bumploc
    Start 8: rrfs_bufr2ioda_msonet
1/8 Test #8: rrfs_bufr2ioda_msonet .....................   Passed   51.60 sec
2/8 Test #1: rrfs_fv3jedi_2024052700_Ens3Dvar ..........***Failed  7832.61 sec
3/8 Test #2: rrfs_fv3jedi_2024052700_getkf_observer ....***Failed  7849.63 sec
    Start 3: rrfs_fv3jedi_2024052700_getkf_solver
4/8 Test #3: rrfs_fv3jedi_2024052700_getkf_solver ......***Failed  345.32 sec`

**Comment by SamuelDegelia-NOAA** [comment]
Hey @keenaneure, I had a look at the ctest log file in `/scratch1/BMC/wrfruc/eure/RDASApp/build/rrfs-test/Testing/Temporary/LastTest.log.tmp` and there is this error: 

`FATAL from PE     0: Disk quota exceeded: netcdf_write_data_3d: file:.//ens3dvar-fv3_lam-C775.fv_core.res.nc variable: ua`

It sounds like the ctests are failing because the wrfruc allocation on scratch1 might is full. Would you be able to build and run the ctests under another project?

**Comment by keenaneure** [comment]
Thanks for checking - I created some space, and this can be closed.
