### ISSUE TITLE
Create the MPAS CONUS_15km case for regional MPAS_JEDI

### ISSUE THREAD

**Issue by xyzemc** [NOAA-EMC/RDASApp#34]
Creating the MPAS CONUS 15-km case on Hera has the following steps:
**1.  Defining the CONUS 15-km domain and subletting the global static fields**

-   Git clone  https://github.com/MPAS-Dev/MPAS-Limited-Area.git
-   Download the global 15-km mesh static file from [MPAS download page](https://mpas-dev.github.io/)
-   Create the run directory (CONUS_15km),  copy MPAS-Limited-Area/docs/points-examples/conus.pts to the run directory and edit it
-   Run "MPAS-Limited-Area/create_region --plot conus.pts mesh/x1.2621442.static.nc"
-   Check the two outputs : CONUS.static.nc & CONUS.graph.info  

**2. Generate ICs and LBCs**
-    Check out and compile MPAS
     Please follow the MPAS [quick start guide](https://docs.google.com/document/d/1tmsOIj0GJDXSuQY7mCwKSfcenwOSj7aTxmzqXX2DLsA/edit) written by Jili Dong   
-    For interpolating the initial conditions using multiple MPI tasks, in the same directory as step 1, and run
    gpmetis -minconn -contig -niter=200 CONUS.graph.info 36
-    Copy namelist.init_atmosphere and streams.init_atmosphere from MPAS_Model that you compiled to the run directory, and edit them
-    Generate initial condition (IC), run
     sbatch < run_init.sh
 

**3. MPAS forecast**

In the same run directory:

-  Link the look-up tables

       ln -sf $YOUR_DIRECTORY/MPAS-Model/src/core_atmosphere/physics/physics_wrf/files/* .

-   Copy namelist and strem files

       cp $YOUR_DIRECTORY/MPAS-Model/namelist.atmosphere .
       cp $YOUR_DIRECTORY/MPAS-Model/streams.atmosphere .
       cp $YOUR_DIRECTORY/MPAS-Model/stream_list.atmosphere.* .

-   Edit the namelist parameters

       eg:
         config_dt
         config_start_time
         config_run_duration
         config_block_decomp_file_prefix

-    Edit job.run_model.sh and run

       sbatch job.run_model.sh

**Comment by guoqing-noaa** [comment]
@xyzemc Do you have the ungribbed intermediate files available on Hera? Thanks!

**Comment by xyzemc** [comment]
> @xyzemc Do you have the ungribbed intermediate files available on Hera? Thanks!

Yes, but I have the ungraded files only for the May 26 case.

**Comment by guoqing-noaa** [comment]
May 26 case works. Could you show me the location of those files? And you static.nc file. Thanks!

**Comment by xyzemc** [comment]
> May 26 case works. Could you show me the location of those files? And you static.nc file. Thanks!

Please try if you can find it under     /scratch1/NCEPDEV/fv3-cam/Xiaoyan.Zhang/mpas/regional/CONUS_15km/

**Comment by guoqing-noaa** [comment]
@xyzemc Is this the case in the current RDASApp?

I followed the instructions here and the result is like this:
![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/1300efe7-918e-4ce3-a84d-f655e29975b2)

**Comment by guoqing-noaa** [comment]
> > May 26 case works. Could you show me the location of those files? And you static.nc file. Thanks!
> 
> Please try if you can find it under `/scratch1/NCEPDEV/fv3-cam/Xiaoyan.Zhang/mpas/regional/CONUS_15km/
`


This directory works. Thank you!

**Comment by xyzemc** [comment]
No, the domain is not the case in current RDASApp.

**Comment by guoqing-noaa** [comment]
OK, got it. So it is this?
![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/93985a0a-ef00-4856-a33d-63a890046565)
