### ISSUE TITLE
Ioda-converters YAML for the RRFS MSONET prepBUFR data

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [NOAA-EMC/RDASApp#38]
**Description**

Write an example YAML for the MSONET prepBUFR RRFS data that converts a BUFR file into an IODA file using the bufr2ioda.x for the following subset:

| MSONET   | A48117 | MESONET SURFACE REPORTS (COOPERATIVE NETWORKS)           |

- [x]  Extract the BUFR table, queries, and important Mnemonics information
- [x]  Use this YAML to convert into an IODA-formatted netCDF file
- [x]  Ioda obs validation using ioda-validate.x
- [x]  Perform validation for the observations using the input BUFR and output IODA file
- [x]  Add output(s) to the testoutput directory
- [ ]  Add tests to the CMakeLists.txt files
- [ ]  Have the tests pass

**Requirements**

- All important mnemonics required by the RRFS users need to be known.

**Acceptance Criteria**

- It will be finished when all files have been checked and tests have passed.

**Dependencies**

- _bufr2ioda.x_

**Comment by PraveenKumar-NOAA** [comment]
**Validation of the output ioda-obs using the ioda-validate.x:** 

**Final results:**
_errors: 0
warnings: 0_

**Comment by PraveenKumar-NOAA** [comment]
Validation of the output IODA results, obtained using the MSONET prepBUFR YAML and bufr2ioda.x, and input prepBUFR file for the following two observations:

**pressure (POB):**
BUFR plot:
![bufr_pressure (2)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/36660692-a000-44f1-9910-41bdeaf7519d)

IODA plot: 
![ioda_pressure (1)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/55aad2a4-413e-46b4-ad9b-a7e90d7dcf8f)


**windEastward (UOB):**
BUFR plot:
![bufr_windEastward (2)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/781b446a-9188-4314-b1b5-b16b72a6bad0)


IODA plot: 
![ioda_windEastward](https://github.com/NOAA-EMC/RDASApp/assets/63739712/b344b291-2ca3-4c03-8d0f-ef66e4edca77)

**Comment by PraveenKumar-NOAA** [comment]
In the the IODA wind plot, there are more observations compaired to the BUFR plot, which are due to the missing values. There are a total of 181121 missing values.

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu @ShunLiu-NOAA please look at the validation plots for the RRFS MSONET prepBUFR data.

**Comment by ShunLiu-NOAA** [comment]
@PraveenKumar-NOAA which test case are you using?

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA which test case are you using?

@ShunLiu-NOAA there is no particular test case I used, these plots are just to make sure that converter is working and creating output as expected.

**Comment by emilyhcliu** [comment]
@PraveenKumar-NOAA What is the datetime of this mesonet data?
Could you dump the header of the IODA file and post it here?
Thanks.

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu @ShunLiu-NOAA message date is  2024050105

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu header of the IODA file: 

netcdf msonet_bufr2ioda {
dimensions:
	Location = 344665 ;
variables:
	int Location(Location) ;
		Location:suggested_chunk_dim = 344665LL ;

// global attributes:
		string :_ioda_layout = "ObsGroup" ;
		:_ioda_layout_version = 0 ;

group: MetaData {
  variables:
  	int64 dateTime(Location) ;
  		dateTime:_FillValue = 9223372036854775807LL ;
  		string dateTime:long_name = "seconds since 1970-01-01T00:00:00Z" ;
  		string dateTime:units = "seconds since 1970-01-01T00:00:00Z" ;
  		string dateTime:coordinates = "longitude latitude" ;
  	float height(Location) ;
  		height:_FillValue = 3.402823e+38f ;
  		string height:long_name = "Height of Observation" ;
  		string height:units = "m" ;
  		string height:coordinates = "longitude latitude" ;
  	float latitude(Location) ;
  		latitude:_FillValue = 3.402823e+38f ;
  		string latitude:long_name = "Latitude" ;
  		string latitude:units = "degrees_north" ;
  		string latitude:coordinates = "longitude latitude" ;
  		latitude:valid_range = -90.f, 90.f ;
  	float longitude(Location) ;
  		longitude:_FillValue = 3.402823e+38f ;
  		string longitude:long_name = "Longitude" ;
  		string longitude:units = "degrees_east" ;
  		string longitude:coordinates = "longitude latitude" ;
  		longitude:valid_range = 0.f, 360.f ;
  	float pressure(Location) ;
  		pressure:_FillValue = 3.402823e+38f ;
  		string pressure:long_name = "Pressure" ;
  		string pressure:units = "Pa" ;
  		string pressure:coordinates = "longitude latitude" ;
  	float stationElevation(Location) ;
  		stationElevation:_FillValue = 3.402823e+38f ;
  		string stationElevation:long_name = "Height of Station" ;
  		string stationElevation:units = "m" ;
  		string stationElevation:coordinates = "longitude latitude" ;
  	string stationIdentification(Location) ;
  		string stationIdentification:_FillValue = "" ;
  		string stationIdentification:long_name = "Station ID" ;
  		string stationIdentification:coordinates = "longitude latitude" ;
  } // group MetaData

group: ObsError {
  variables:
  	float airTemperature(Location) ;
  		airTemperature:_FillValue = 3.402823e+38f ;
  		string airTemperature:long_name = "Temperature Error" ;
  		string airTemperature:units = "K" ;
  		string airTemperature:coordinates = "longitude latitude" ;
  	float pressure(Location) ;
  		pressure:_FillValue = 3.402823e+38f ;
  		string pressure:long_name = "Pressure Error" ;
  		string pressure:units = "Pa" ;
  		string pressure:coordinates = "longitude latitude" ;
  	float relativeHumidity(Location) ;
  		relativeHumidity:_FillValue = 3.402823e+38f ;
  		string relativeHumidity:long_name = "Relative Humidity Error" ;
  		string relativeHumidity:units = "1" ;
  		string relativeHumidity:coordinates = "longitude latitude" ;
  	float windEastward(Location) ;
  		windEastward:_FillValue = 3.402823e+38f ;
  		string windEastward:long_name = "Eastward Wind Error" ;
  		string windEastward:units = "m s-1" ;
  		string windEastward:coordinates = "longitude latitude" ;
  	float windNorthward(Location) ;
  		windNorthward:_FillValue = 3.402823e+38f ;
  		string windNorthward:long_name = "Northward Wind Error" ;
  		string windNorthward:units = "m s-1" ;
  		string windNorthward:coordinates = "longitude latitude" ;
  } // group ObsError

group: ObsValue {
  variables:
  	float airTemperature(Location) ;
  		airTemperature:_FillValue = 3.402823e+38f ;
  		string airTemperature:long_name = "Temperature" ;
  		string airTemperature:units = "K" ;
  		string airTemperature:coordinates = "longitude latitude" ;
  	float dewPointTemperature(Location) ;
  		dewPointTemperature:_FillValue = 3.402823e+38f ;
  		string dewPointTemperature:long_name = "Dew Point Temperature" ;
  		string dewPointTemperature:units = "K" ;
  		string dewPointTemperature:coordinates = "longitude latitude" ;
  	float specificHumidity(Location) ;
  		specificHumidity:_FillValue = 3.402823e+38f ;
  		string specificHumidity:long_name = "Specific Humidity" ;
  		string specificHumidity:units = "kg kg-1" ;
  		string specificHumidity:coordinates = "longitude latitude" ;
  	float virtualTemperature(Location) ;
  		virtualTemperature:_FillValue = 3.402823e+38f ;
  		string virtualTemperature:long_name = "Virtual Temperature Non-Q Controlled" ;
  		string virtualTemperature:units = "K" ;
  		string virtualTemperature:coordinates = "longitude latitude" ;
  	float windEastward(Location) ;
  		windEastward:_FillValue = 3.402823e+38f ;
  		string windEastward:long_name = "Eastward Wind" ;
  		string windEastward:units = "m s-1" ;
  		string windEastward:coordinates = "longitude latitude" ;
  	float windNorthward(Location) ;
  		windNorthward:_FillValue = 3.402823e+38f ;
  		string windNorthward:long_name = "Northward Wind" ;
  		string windNorthward:units = "m s-1" ;
  		string windNorthward:coordinates = "longitude latitude" ;
  } // group ObsValue

group: QualityMarker {
  variables:
  	int airTemperature(Location) ;
  		airTemperature:_FillValue = 2147483647 ;
  		string airTemperature:long_name = "Temperature Quality Marker" ;
  		string airTemperature:coordinates = "longitude latitude" ;
  	int height(Location) ;
  		height:_FillValue = 2147483647 ;
  		string height:long_name = "Height Quality Marker" ;
  		string height:coordinates = "longitude latitude" ;
  	int pressure(Location) ;
  		pressure:_FillValue = 2147483647 ;
  		string pressure:long_name = "Pressure Quality Marker" ;
  		string pressure:coordinates = "longitude latitude" ;
  	int specificHumidity(Location) ;
  		specificHumidity:_FillValue = 2147483647 ;
  		string specificHumidity:long_name = "Specific Humidity Quality Marker" ;
  		string specificHumidity:coordinates = "longitude latitude" ;
  	int windEastward(Location) ;
  		windEastward:_FillValue = 2147483647 ;
  		string windEastward:long_name = "U, V-Component of Wind Quality Marker" ;
  		string windEastward:coordinates = "longitude latitude" ;
  	int windNorthward(Location) ;
  		windNorthward:_FillValue = 2147483647 ;
  		string windNorthward:long_name = "U, V-Component of Wind Quality Marker" ;
  		string windNorthward:coordinates = "longitude latitude" ;
  } // group QualityMarker
}

**Comment by PraveenKumar-NOAA** [comment]
<img width="353" alt="Screenshot 2024-05-15 at 1 30 27 PM" src="https://github.com/NOAA-EMC/RDASApp/assets/63739712/7f1010ed-6ae7-4a74-84a0-5b8fafcb0bb0">

<img width="391" alt="Screenshot 2024-05-15 at 1 30 46 PM" src="https://github.com/NOAA-EMC/RDASApp/assets/63739712/bbd870d1-c731-4371-a223-64f8bf449a77">

**Comment by ShunLiu-NOAA** [comment]
@PraveenKumar-NOAA Thank you for the information. Do you get prepbufr file for RDAS test case on 2022052619?

**Comment by PraveenKumar-NOAA** [comment]
@ShunLiu-NOAA @emilyhcliu please look at these plots created for the RDAS test case, dated 2022052619: 

**pressure (POB):**
BUFR plot:
![bufr_pressure (3)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/d9eec616-f13c-47ce-8bac-59dca6851dff)

IODA plot:
![ioda_pressure (2)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/7ac5fe67-e355-439a-902b-00dd53c8844a)

**windEastward (UOB):**
BUFR plot:
![bufr_windEastward (3)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/cbe1f43d-1240-4e54-8280-ff0c632c036a)


IODA plot:
![ioda_windEastward (1)](https://github.com/NOAA-EMC/RDASApp/assets/63739712/8cdb37e8-a910-450e-9c2a-63721277c461)

**Comment by PraveenKumar-NOAA** [comment]
Extra total counts or observations in the IODA wind plot are due to the missing values, 163698. 
@ShunLiu-NOAA let me know if you have any questions about these plots and need something else. The converter is ready to use.

**Comment by ShunLiu-NOAA** [comment]
Thank you. Could you convert all data type in this prepbufr file to IODA following RDAS_JEDI_observation (https://docs.google.com/spreadsheets/d/16AUjgDDHLRhVdy5fcg1DNwEtoDSOM89z9m_9VaPy50k/edit?usp=sharing)

**Comment by PraveenKumar-NOAA** [comment]
A PR is merged for mesonet prepBUFR, so I am closing this issue.
