### ISSUE TITLE
MPAS-JEDI case: LETKF vs 3DEnVar

### ISSUE THREAD

**Issue by SamuelDegelia-NOAA** [NOAA-EMC/RDASApp#39]
I am working on adding a yaml and ctest for LETKF in MPAS JEDI and am seeing some weird results when comparing against the 3DEnVar case added in #16. 

Below are the model level 10 temperature increments comparing between 1) 3DEnVar, 2) 3DEnVar using the ensemble mean as the background, and 3) LETKF. Theoretically, 2) and 3) should be pretty similar if localization is equivalent. The LETKF is configured with horizontal localization of 1000 km and vertical localization of 6 km, which I believe is the same used for the 3DEnVar test case. Also, the observations are overlaid as yellow dots (sondes) and cyan dots (RASS aircraft obs). 

According to the log files, the same number of observations are used in each experiment. However, there are some weird circular artifacts that appear in the 3DEnVar experiments over the Western Plains and Rockies (other parts of the domain show these artifacts but it is most obvious in these regions). There are also little-to-no increments associated with the observations in central Illinois in 3DEnVar, whereas there are large increments in LETKF.

I am still not familiar with how localization is performed for 3DEnVar in JEDI and BUMP, but is this behavior to be expected with the very small ensemble size? Or do you think that this might be indicative of a problem with the MPAS test case? 

1. 3DEnVar
![increment_airTemperature_withobs_envar](https://github.com/NOAA-EMC/RDASApp/assets/167246325/afcf25de-b4bd-43dd-bbf2-4389fd78471a)

2. 3DEnVar with ensemble mean background
![increment_airTemperature_withobs_envar_bgensmean](https://github.com/NOAA-EMC/RDASApp/assets/167246325/cdd6f08f-04d0-4c6e-85a6-061d8baa2281)

3. LETKF
![increment_airTemperature_withobs_1000km](https://github.com/NOAA-EMC/RDASApp/assets/167246325/fef1f5f9-66f3-4cbe-a330-6b7a5db8cd35)

**Comment by ShunLiu-NOAA** [comment]
@SamuelDegelia-NOAA Thanks for comparing LETKF and 3DEnVar. Let's talk about this at today's RRFS DA group meeting with GSL. I think we need to build a more realistic test case with a reasonable number of ensemble members. BUMP and static B are now a under discussion now.

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA   That is great to see those comparison between letkf and 3denvar.  To help clarify any potential issues, I would suggest to start from oneob test (one ob on_fly) .

**Comment by SamuelDegelia-NOAA** [comment]
@TingLei-NOAA Good idea, I'll try some one ob tests and compare between LETKF and EnVar.

**Comment by SamuelDegelia-NOAA** [comment]
Here are some single observation tests using the mesonet temperature observation from Donnie. The plots are temperature increments at model level 10. The EnVar test here uses the ensemble mean as the background for better comparison against LETKF. 

The comparison for the single observation test looks better than the larger observation suite. However, the differences are still larger than I would expect, especially in southern Florida where the increments become small for EnVar. I am next going to plot the covariance between surface temp and other grid points to see which flavor of DA matches what we would expect. 

![comparison](https://github.com/NOAA-EMC/RDASApp/assets/167246325/477edc90-8fe6-4057-be21-b49e1b81ad7d)

**Comment by SamuelDegelia-NOAA** [comment]
Here is the covariance between H(x) and the background temperature at model level 10. This plot is very consistent with the LETKF increment which confirms that LETKF is working as expected. This also means that there is likely some kind of issue with EnVar. It is possible that this is a result of the small domain size, so I will wait to investigate further until we build a more realistic test case for MPAS. 

![covar_airTemperature](https://github.com/NOAA-EMC/RDASApp/assets/167246325/59d43034-623b-480b-a037-193d4560e36b)

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA Very interesting findings .  seems there is really some issue with the 3dEnvar. While, could you use upper level one ob test to see how it goes?  You can use that kind of online obtest (namely without need to prepare actual obs) as in hofx_nomodel_lam_rrfs_obs_on_lbc.yaml

**Comment by SamuelDegelia-NOAA** [comment]
@TingLei-NOAA Here is a comparison with a temperature observation at 3 km AGL (using the GenList tool to generate a single observation online). The same problem occurs here with some weird artifacts showing up in the EnVar increment. I circled a region in the EnVar increment where I am seeing one of these straight lines show up in the increments. It seems like there could be some kind of issue with the gridding though I am not sure what. Also, I should note that I did a similar comparison for FV3-JEDI and the increment structures match very closely. So the problem is possibly related to MPAS' unstructured grid. 

<img width="1087" alt="comparison" src="https://github.com/NOAA-EMC/RDASApp/assets/167246325/393d0734-af57-44e5-8ce7-faee73ca4ec7">

My next step is to rerun BUMP_NICAS at a higher resolution to see if that improves this issue at all.

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA  Yes. that discontinuity you flagged is very suspicious. And we can see multiple similar discontinuities in the mpas-jedi increment.   Is it an issue specific to regional runs or not? A comprehensive investigation is needed. 
I would recommend first to open an issue on mpas-jedi to bring this valuable findings/case to the attention of mpas-jedi core team.

**Comment by SamuelDegelia-NOAA** [comment]
@TingLei-NOAA Good idea, will do!

**Comment by SamuelDegelia-NOAA** [comment]
I believe I found the issue. Rerunning BUMP to generate the ensemble localization files with higher resolution causes these artifacts to go away. The nicas resolution variable is detailed further [here](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/saber/BUMP_saber_blocks.html). 

```
      nicas:
        #resolution: 4.0 # previous
        resolution: 8.0
        explicit length-scales: true
        horizontal length-scale:
          - groups: [common]
            value: 1000.0e3
```


After rerunning EnVar with the new ensemble localization files, the LETKF and EnVar increments now look very similar and are about what I would expect: 

![comparison](https://github.com/NOAA-EMC/RDASApp/assets/167246325/c940e368-7a91-4f2c-9118-f86cf2cd4e95)

We should not need a PR to fix this, since I can just overwrite the staged input data in `rrfs-test-data/rrfs-data_mpasjedi_2022052619/DataFix/bump_new` on Orion and Hera. In the future, if we include any yaml files for running BUMP, we should make sure that the resolution is set to 8.0

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA  Great for you to find the reason for that issue!
Could you use the new bump files to replace the original one?

**Comment by ShunLiu-NOAA** [comment]
@SamuelDegelia-NOAA It is great to figure this out. Please update test case if necessary.

**Comment by SamuelDegelia-NOAA** [comment]
@TingLei-NOAA Yes, I should just be able to overwrite the old bump files with my new ones. Nothing needs to change in the yaml files for EnVar. I will also make sure I update the test reference files @ShunLiu-NOAA

**Comment by SamuelDegelia-NOAA** [comment]
When assimilating the full set of observations for our RDAS case, there are still some large differences between EnVar and LETKF increments. Increasing the BUMP resolution solved a lot of problems in that the artifacts are gone, but there still seem to be some regions where EnVar has little-to-no increments compared to LETKF (see obs. in central Illinois). I am continuing to investigate this problem and plan to try and grab some of those aircraft obs. over Illinois to run single observation tests. 

1. EnVar 
![increment_airTemperature_withobs_envar](https://github.com/NOAA-EMC/RDASApp/assets/167246325/9ed64faa-1100-4900-8b94-6312b05c9eef)

2. LETKF
![increment_airTemperature_withobs_1000km](https://github.com/NOAA-EMC/RDASApp/assets/167246325/e40a09de-87a7-4855-993c-81106bdc6a8f)

**Comment by delippi** [comment]
@SamuelDegelia-NOAA, don't forget to try changing DRIPCG to DRPCG. I thought I had eliminated DRIPCG from our yamls, but it keeps coming back since new yamls might not be based on the most up to date version. We should double check that people DO NOT use DRIPCG in the future.

**Comment by SamuelDegelia-NOAA** [comment]
Luckily the MPAS yamls we have all use DRPCG so it shouldn't be causing this problem specifically. It is the `rrfs_fv3jedi_hyb_2022052619.yaml` in the repository that still has DRIPCG set. I can go ahead and make a PR to change that yaml to be sure that we aren't using DRIPCG.

**Comment by SamuelDegelia-NOAA** [comment]
The issue in my last post with missing increments over Illinois was due to different time window settings between LETKF and EnVar. I accidentally used a larger time window in LETKF causing more sonde obs. to be assimilated compared to EnVar. But either way, rerunning LETKF and EnVar with the BUMP resolution fix and the same time window leads to the increments looking fairly similar between EnVar and LETKF. See new versions of the increment plots below. 

There are still some differences, mainly in magnitude and maximum radius of the impacts. But I think those differences are likely explained by differences in localization methods. Overall the structure and shape of the increments is the same, so I think EnVar for MPAS-JEDI is now performing as expected after correcting the BUMP resolution. I'll leave the issue open for a little bit to see if anyone else has thoughts. 

EnVar: 
![increment_airTemperature_withobs_envar_9](https://github.com/NOAA-EMC/RDASApp/assets/167246325/dcdbe881-f3df-4091-ba8d-96feeb5138f8)

LETKF: 
![increment_airTemperature_withobs_letkf_9](https://github.com/NOAA-EMC/RDASApp/assets/167246325/307c0d7c-da78-4b11-ad50-3f10d4a95706)
