### ISSUE TITLE
cannot access /work2/noaa/fv3-cam/sdegelia/RRFS/rrfs-test-data

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#43]
@SamuelDegelia-NOAA 

Could you make your rrfs-test-data directory on Orion readable by everyone? Thanks!

**Comment by guoqing-noaa** [comment]
also on Hera, I got "permission denied" for the following file:

`/scratch1/NCEPDEV/da/Samuel.Degelia/RRFS/rrfs-test-data/rrfs-data_mpasjedi_2022052619/DataFix/bump_new/bumploc_conus15km_highres.yaml`

**Comment by SamuelDegelia-NOAA** [comment]
The permission issue for `bumploc_conus15km_highres.yaml` on Hera should be fixed - that file was just added today. But I'm not sure why the permissions are acting up on Orion. I just reset them there, could you try again?

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks for your quick fix. It worked now.

**Comment by SamuelDegelia-NOAA** [comment]
Great, glad it is working now! Sorry about that.
