### ISSUE TITLE
 CMake Error: failed to create symbolic link for mem000 for the fv3 case

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#44]
The error message is as follows:

`CMake Error: failed to create symbolic link '/work2/noaa/wrfruc/gge/RDASApp/build/fv3-jedi/test/Data/inputs/gfs_c12/mem000': Permission denied            `          

The related CMake command is at lines 568-570 of `sorc/fv3-jedi/test/CMakeLists.txt`

'''
execute_process( COMMAND ${CMAKE_COMMAND} -E create_symlink
               ${CMAKE_CURRENT_BINARY_DIR}/Data/inputs/gfs_c12/bkg
               ${CMAKE_CURRENT_BINARY_DIR}/Data/inputs/gfs_c12/mem000)
'''

The reason for this error is that the inputs/gfs_c12 directory is a link to a directory owned by Cory Martin:

`build/fv3-jedi/test/Data/inputs -> /work2/noaa/wrfruc/gge/RDASApp/bundle/fv3-jedi-data/testinput_tier_1/inputs/
/work2/noaa/wrfruc/gge/RDASApp/bundle/fv3-jedi-data -> /work2/noaa/da/cmartin/CI/RDASApp/data/jcsda/fv3-jedi-data/
`

Do we need mem000? If not, we can remove lines 568-570; if yes, we may want to fix this error.

**Comment by SamuelDegelia-NOAA** [comment]
@CoryMartin-NOAA Could you check the permissions for your staged fv3-jedi test data on Orion? I haven't had this issue, but the problem could be because @guoqing-noaa is not on the `da` account on Orion.

**Comment by guoqing-noaa** [comment]
Thanks, @SamuelDegelia-NOAA and @CoryMartin-NOAA !

I'd like to add that I got the same error on Hera:

`CMake Error: failed to create symbolic link '/scratch1/BMC/wrfruc/gge/RDASApp/build/fv3-jedi/test/Data/inputs/gfs_c12/mem000': Permission denied        `

**Comment by CoryMartin-NOAA** [comment]
Can you give me more info on this? Is this re-running cmake for an existing build? There shouldn't be permissions issues on Hera. I've seen a warning like this before but it still compiles, is that the case?

**Comment by guoqing-noaa** [comment]
@CoryMartin-NOAA Yes, it can compile.

I am curious whether we need mem000. Thanks!

**Comment by CoryMartin-NOAA** [comment]
It's something in fv3-jedi, so it's not something we can just change in RDASApp. My guess is there is at least one test that needs it.

**Comment by guoqing-noaa** [comment]
Thanks for the information!

**Comment by SamuelDegelia-NOAA** [comment]
@CoryMartin-NOAA Thanks for the clarification! Since this issue is specific to fv3-jedi and not RDASApp, and since everything still builds successfully, are we okay with closing this issue here?

**Comment by guoqing-noaa** [comment]
I ran lots of SkyLab (FV3) experiments and did not got this kind of error. 
I think it is still related to how to coordinate RDASApp with fv3-jedi.  

However, it is fine to close this ticket as this error does not stop building and we will focus on MPAS cases going forward.
Thanks!

**Comment by CoryMartin-NOAA** [comment]
This is because we don't want every user downloading test data if we don't have to, and instead it links it from one download. That's why you don't see it with skylab

**Comment by guoqing-noaa** [comment]
Close this ticket since we will move forward with MPAS cases instead of FV3 cases.
