### ISSUE TITLE
Test satellite radiance bias correction for ATMS NPP in MPAS-JEDI

### ISSUE THREAD

**Issue by xyzemc** [NOAA-EMC/RDASApp#52]
For applying the satellite radiance bias correction in JEDI, there are some pre-process steps:

1. convert the gsi satbias and satbias_pc files to ioda format with [GSI satbias converter](https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/gsi_varbc/README.md) 

  -  link RDASApp/build/bin/satbias2ioda.x to your_work_directory  (NOTE: copy will not work)

  -  create satbias_converter.yaml 

> 

          input coeff file: ./rrfs.spinup.2023042720_satbias
          input err file: ./rrfs.spinup.2023042720_satbias_pc
          default predictors: &default_preds
          - constant
          - zenith_angle
          - cloud_liquid_water
          - lapse_rate_order_2
          - lapse_rate
          - cosine_of_latitude_times_orbit_node
          - sine_of_latitude
          - emissivity
          - scan_angle_order_4
          - scan_angle_order_3
          - scan_angle_order_2
          - scan_angle
          output:
          - sensor: atms_npp
            output file: satbias_atms_npp.nc4
            predictors: *default_preds
          - sensor: atms_n20
            output file: satbias_atms_n20.nc4
            predictors: *default_preds

 - Create the tlaps file manually by copying the 2-4 columns of the instrument 
     atms_npp.tlapse.txt

>
   
    atms_npp 1 0.242396E+00
    atms_npp 2 0.161521E+00
    atms_npp 3 0.122284E+01
    atms_npp 4 0.184939E+01
    atms_npp 5 0.276065E+01
    atms_npp 6 0.343459E+01
    atms_npp 7 0.347138E+01
    atms_npp 8 0.249312E+01
    atms_npp 9 0.124182E+01
    atms_npp 10 -0.104760E+01
    atms_npp 11 -0.268708E+01
    atms_npp 12 -0.534154E+01
    atms_npp 13 -0.828398E+01
    atms_npp 14 -0.726963E+01
    atms_npp 15 -0.251210E+01
    atms_npp 16 0.433186E+00
    atms_npp 17 0.153876E+01
    atms_npp 18 0.291233E+01
    atms_npp 19 0.381283E+01
    atms_npp 20 0.461646E+01
    atms_npp 21 0.554495E+01
    atms_npp 22 0.619940E+01

2. To convert GSI bias correction coefficient files (satbias_in and satbias_pc), run satbias2ioda.x executable, passing it a yaml configuration file:

> 
     satbias2ioda.x satbias_converter.yaml
The output is: satbias_atms_npp.nc4

3. Copy these three files to Data/obs

> 
    cp satbias_atms_npp.nc4 Data/obs/.
    cp satbias_atms_npp.nc4 Data/obs/satbias_atms_npp_cov.nc4
    cp atms_npp.tlapse.txt Data/obs/.

  
4. Modify the YAML file to add the bias correction

> 
     obs bias:
         input file:  Data/obs/atms_npp.satbias.nc4
         output file: Data/bc/out_atms_npp.satbias.nc
         variational bc:
           predictors:
           - name: constant
           - name: lapse_rate
             order: 2
             tlapse: &atms_npp_tlapse  Data/obs/atms_npp.tlapse.txt
           - name: lapse_rate
             tlapse: *atms_npp_tlapse
           - name: emissivity
           - name: scan_angle
             order: 4
           - name: scan_angle
             order: 3
           - name: scan_angle
             order: 2
           - name: scan_angle
         covariance:
           minimal required obs number: 20
           variance range: [1.0e-6, 10.0]
           step size: 1.0e-4
           largest analysis variance: 10000.0
           prior:
             input file: Data/obs/atms_npp.satbias_cov.nc4
             #input file: /scratch1/NCEPDEV/fv3-cam/Xiaoyan.Zhang/mpas_jedi_conus/satbias_atms_Emily/gdas.t18z.atms_npp.satbias_cov.nc4
             #input file: Data/obs/atms_npp.satbias_cov_2022052619.nc4
             inflation:
               ratio: 1.1
               ratio for small dataset: 2.0
           output file: Data/bc/out_atms_npp.satbias_cov.nc

**Comment by xyzemc** [comment]
Histogram plot for O-B with/without bias correction:
![image](https://github.com/NOAA-EMC/RDASApp/assets/45010998/afd5c526-9a85-4e65-97ba-20ee1b203c28)

**Comment by guoqing-noaa** [comment]
@xyzemc Do you have special considerations for using satbias files from a **spin-up** cycle?

**Comment by xyzemc** [comment]
> @xyzemc Do you have special considerations for using satbias files from a **spin-up** cycle?

Nothing special. Just follow what RRFS is doing now to use the RRFS satbias file for a spin-ip cycle, or start from a zero satbias file.

**Comment by keenaneure** [comment]
Thank you for providing these instructions! I just wanted to mention that when I copy the satbias2ioda.x to the working directory, I am not able to run it. However, if it is soft linked from the bin/ directory, it works fine on my end.

**Comment by xyzemc** [comment]
> Thank you for providing these instructions! I just wanted to mention that when I copy the satbias2ioda.x to the working directory, I am not able to run it. However, if it is soft linked from the bin/ directory, it works fine on my end.

It is weird. Thanks for report this.

**Comment by SamuelDegelia-NOAA** [comment]
This might be similar to what @guoqing-noaa reported for bufr2ioda in #145.

**Comment by guoqing-noaa** [comment]
> This might be similar to what @guoqing-noaa reported for bufr2ioda in #145.

@SamuelDegelia-NOAA Right. The same issue as bufr2ioda.x.
@xyzemc I made a minor change to your instruction to let user `link` satbias2ioda.x instead of `copy`.

**Comment by keenaneure** [comment]
Hi Xiaoyan,

Where does one find rrfs.spinup.2023042720_satbias and rrfs.spinup.2023042720_satbias_pc (or maybe for 20240527 instead)?

**Comment by xyzemc** [comment]
> Hi Xiaoyan,
> 
> Where does one find rrfs.spinup.2023042720_satbias and rrfs.spinup.2023042720_satbias_pc (or maybe for 20240527 instead)?

If you run the 20240527 case, you need the satbias at this time too. The 'rrfs.spinup.2023042720_satbias' probably for the old case test.

**Comment by keenaneure** [comment]
I am running the 2024052700 case. Is this renamed from satbias_crtm_in/satbias_crtm_pc, does this exist at another pathway in JCSDA-internal, or does it need to be produced by the user before running satbias2ioda.x?

**Comment by xyzemc** [comment]
> I am running the 2024052700 case. Is this renamed from satbias_crtm_in/satbias_crtm_pc, does this exist at another pathway in JCSDA-internal, or does it need to be produced by the user before running satbias2ioda.x?
Yes, the 2024052700 atms satbias files are under /scratch2/BMC/rtrr/RDAS_DATA/fix/expr_data/obs_2024052700, and they were renamed to: 
atms_n20.satbias.nc4  atms_n20.satbias_cov.nc4 
atms_npp.satbias.nc4  atms_npp.satbias_cov.nc4

**Comment by keenaneure** [comment]
It seems like atms_n20.satbias.nc4, atms_n20.satbias_cov.nc4, atms_npp.satbias.nc4, and atms_npp.satbias_cov.nc4 are created after step 2. I am confused - where or how do you get the files in order to complete step 1? I see rrfs.spinup.2023042720_satbias and rrfs.spinup.2023042700_satbias_pc in lines 1-2 of satbias_converter.yaml, but my guess is that different files would be needed for the 2024052700 case, and if I wanted to do this process for the atms_n21 sensor. When I checked [satbias_crtm_in](https://github.com/JCSDA-internal/ioda-converters/blob/develop/test/testinput/satbias_crtm_in), there is nothing listed for atms_n21.
