### ISSUE TITLE
Problem found  in processing the observation at the domain boundary

### ISSUE THREAD

**Issue by xyzemc** [NOAA-EMC/RDASApp#6]
When try to assimilate goes_16 ABI radiance data in RRFS CONUS domain, there are error messages like:
--------------------------------------------------------------------------------------------------
61:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.8427
78:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.3020
70:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.5450
64:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.8539
 0:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.1657
59:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.7820
42:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.4165
14:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.8745
46:  CRTM_Surface_IsCoverageValid(INFORMATION) : Total coverage fraction does not sum to 1 +/-  1.000000000000000E-06  0.9874
---------------------------------------------------------------------------------------------------
After debugging, I found all those points are on the right side of domain edge. See plots below:
Surface total fraction: land+water+ice+snow
![image](https://github.com/NOAA-EMC/RDASApp/assets/45010998/54ec57bb-bb2a-4503-9f26-f7a7831ab402)

Similar issue happened to other input variables required by CRTM:
Air_temperature has 0 values on those points:
![image](https://github.com/NOAA-EMC/RDASApp/assets/45010998/4bd05f90-2672-42a4-a42e-fc0864a546bd)

**Comment by TingLei-daprediction** [comment]
@xyzemc  Would you try this draft PR https://github.com/JCSDA-internal/fv3-jedi/pull/1096  to see if it could avoid this issue? 
Or you can directly use the built branch on hera: /scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-jedi-bundle/jedi-bundle/build/bin/?

**Comment by xyzemc** [comment]
This issue has been solved.
