### ISSUE TITLE
how to update wiki?

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#62]
Is there a way to update the wiki by the community? Can we track the modification history?

If NOT, we may want to create a `doc/` subdirectory to hold RDASApp-related documents, including a quick Readme.md.
This way, everyone may contribute to the documentation and a review process can be enforced. Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
You can see the modification history for the wiki by clicking the "XX revisions" link at the top of any of the pages. But as far as I know there is no way to have PRs for those changes. I think a quick README.md file would be helpful, at least with build instructions. But I think some of the more detailed instructions, like for the one-ob test, are better left for the wiki. 

To update the wiki, you should just be able to hit the edit page at the top. But maybe you need permissions for this?

**Comment by guoqing-noaa** [comment]
Thanks! @SamuelDegelia-NOAA 
I think some contents in the documentation are tied with specific commits of the repo. Those documents will be better to include as one part of the repo. Wiki may hold some general things regardless of the changed versions.

No, I cannot see any "edit" buttons/links.

**Comment by SamuelDegelia-NOAA** [comment]
@CoryMartin-NOAA Could you add Guoqing as a repository collaborator so that he can edit the wiki? 

Also, I agree that the wiki documentation changes frequently so it would be nice to track/approve those changes as part of the repo. But I also think that the layout on the wiki pages makes it much easier to follow a tutorial like for the one-ob test. So I'll do a little more digging on if there is a way to commit to the wiki.

**Comment by CoryMartin-NOAA** [comment]
@guoqing-noaa see if you have access now

**Comment by guoqing-noaa** [comment]
Thanks @CoryMartin-NOAA! I saw the "edit" button now.

**Comment by SamuelDegelia-NOAA** [comment]
FYI I found out about this GitHub Action (https://github.com/marketplace/actions/github-wiki-action) that can sync files between the Wiki and repository (e.g., files in `docs/`). This allows you to commit and have PRs for the wiki, and could be an option in the future if we wanted.

**Comment by guoqing-noaa** [comment]
That's great news! Thanks, @SamuelDegelia-NOAA 
We should try this.

**Comment by SamuelDegelia-NOAA** [comment]
I can try and get it working on my fork and report back.
