### ISSUE TITLE
git status --ignore-submodules

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#65]
I am not sure whether this is an issue for others. Or it might already be documented.

`git status` is substantially slower sometimes for this repo as it contains 17 submodules. 

By default, when you run `git status` in a repo with submodules, it'll recursively run `git status `in every submodule (sequentially). `git diff` behaves similarly to `git status`. Pre-commit appears to run` git status` once at the beginning and then runs `git diff` before and after each hook (to detect any changes made by the hook). All these git operations will sometimes become substantially slower for a repo with many submodules.

Since we most likely will not update submodule contents while working on RDASApp, we can add a command line option `--ignore-submodules` to make normal git operations much faster.  However, it will be sweeter if there is a way to make this the default option.

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  Good point!  However, will this be done by developers themselves like by setting up their own alias after this issue is documented ,say, in the wiki?     
Another way is to have a setup in rdas module file to add an alias like status_v1 , but to let the developers know it is not straightforward  and maybe it also need to be done by the wiki.   But, then, I will prefer the users/developers add the alias by themselves.

**Comment by TingLei-NOAA** [comment]
And, another way is not to run "git status" in the root dir and just run it in the component the developer is interested in. I think in that case, only "status" in the current project/submodule would be checked out.

**Comment by SamuelDegelia-NOAA** [comment]
The behavior @guoqing-noaa describes can be made default by adding an `ignore = dirty` line in the `.gitmodules` file like so: 

```
[submodule "sorc/crtm"]
        path = sorc/crtm
        url = https://github.com/jcsda/crtm
        branch = release/crtm_jedi_v2.4.1
        ignore = dirty
```

This speeds up `git status` significantly. You could also choose `ignore = all` to suppress all output and comparisons for the submodules altogether. See the difference of all and dirty [here](https://stackoverflow.com/a/41598706). 

Whether we want to do this is up for discussion though. I think a few people might be using the base RDASApp to also make code changes to some of the submodules like UFO, fv3-jedi, mpas-jedi etc. This change might make it harder to track those developments and in that case just recommending an alias via the wiki could be better. But I welcome any input there.

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA  According to chatgpt (:)) :
```
ignore = dirty: This line specifies how Git should handle changes in the submodule. Setting ignore to dirty means that Git will ignore uncommitted changes in the submodule when running commands like git status in the parent repository. This can be useful to prevent seeing changes in the submodule that you are not ready to commit.
``` 
This option could help speeding up for "git status" but has far more impacts than it, which I think make is not a solution for this issue.

**Comment by SamuelDegelia-NOAA** [comment]
@TingLei-NOAA Isn't adding the `ignore = dirty` line (or `ignore = all`) the same idea as running `git status --ignore-submodules`? Or I might be misunderstanding something.

**Comment by guoqing-noaa** [comment]
Thanks, @SamuelDegelia-NOAA and @TingLei-NOAA for discussions!  

People have mixed feeling (love and hate :) ) about git submodules. They have some advantages, but they also have many disadvantages. There are so many good debate/discussions about git submodules on the internet.

My preference would be avoiding submodules if possible. I think the external management scripts in rrfs-workflow for including other dependent repos work very well.  

I don't mean we need to move away from git submodules for RDASApp. Just want to bring this issue up for awareness. 

Thanks @SamuelDegelia-NOAA and @TingLei-NOAA for viable solutions! Adding "ignore" to .gitmodules looks a reasonable solution to me.

**Comment by TingLei-NOAA** [comment]
> @TingLei-NOAA Isn't adding the `ignore = dirty` line (or `ignore = all`) the same idea as running `git status --ignore-submodules`? Or I might be misunderstanding something.

Yes, you are right.   After some further digging,  adding "ignore=dirty"  is the same as  running  "git status --ignore".  Then the trivial difference is if the developers are aware of this "ignore" option if  ignore=dirty is added.        So, I would agree , as @guoqing-noaa , adding this option is indeed the solution.

**Comment by guoqing-noaa** [comment]
At some point, we will need to test frozen snapshots of RDASApp as we move forward. It is not straightforward to check this for git submodules.

For example, check this file:
https://github.com/guoqing-noaa/RDASApp/blob/submodule.test/.gitmodules

I have intentionally reverted the ioda component to a previous commit (#776f9998) but you cannot find that information in the .gitmodules file, it is always like this:
```
[submodule "sorc/ioda"]
	path = sorc/ioda
	url = https://github.com/jcsda/ioda
	branch = develop
```

Although we can use a command like "`git ls-tree submodule.test sorc/ioda`" to retrieve the top commit hash# of the ioda component, it is not straightforward and requires a clone and submodule update to do so.

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  Will "git log -S776f9998 -- sorc/ioda"  give the information ( the parent hash numbers (top commit hash number)  corresponding the 776f9998 of sorc/ioda"?

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA `git log -S776f9998 -- sorc/ioda` did not work for getting the HEAD commit of the submodules.

Normally, we would expect to know the current HEAD commits for each submodule snapshots without cloning and git operations, similar like this: https://github.com/NOAA-EMC/rrfs-workflow/blob/dev-sci/sorc/Externals.cfg

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa See your point. I think those information could be got by "git submodule status" 
To get such a informative  file as you gave,  we can have an shell script in the repo to scan the app From chatgpt, such a  file is as :
```
#!/bin/bash
#clt from chatgpt
# Define the output config file
OUTPUT_FILE="project_config.ini"

# Get the hash of the parent project
PARENT_HASH=$(git rev-parse HEAD)

# Start writing to the config file
echo "[parent_project]" > $OUTPUT_FILE
echo "hash = $PARENT_HASH" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE

# Get the list of submodules
SUBMODULES=$(git submodule status | awk '{print $2}')

# Iterate over each submodule
for submodule in $SUBMODULES; do
    # Get the details of the submodule
    cd $submodule
    SUBMODULE_HASH=$(git rev-parse HEAD)
    SUBMODULE_URL=$(git config --get remote.origin.url)
    SUBMODULE_NAME=$(basename $submodule)
    cd - > /dev/null

    # Append the submodule details to the config file
    echo "[$SUBMODULE_NAME]" >> $OUTPUT_FILE
    echo "protocol = git" >> $OUTPUT_FILE
    echo "repo_url = $SUBMODULE_URL" >> $OUTPUT_FILE
    echo "# Specify either a branch name or a hash but not both." >> $OUTPUT_FILE
    echo "#branch = " >> $OUTPUT_FILE
    echo "hash = $SUBMODULE_HASH" >> $OUTPUT_FILE
    echo "local_path = $submodule" >> $OUTPUT_FILE
#    echo "required = True" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
done

echo "Configuration file created: $OUTPUT_FILE"
```.   it works for me and please see if it is the tool you think is appropriate to add to gdasapp (maybe we could add a dir to hold all those tools).

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA Thumbs up for the ChatGPT help! 😊

`git submodule status` works well, much better than my previous awkward command. Thanks!

**Comment by guoqing-noaa** [comment]
As discussed here, we will need extra steps to work effectively with submodules. This also requires general users to have some knowledge of submodules. I encountered lots of users who got confused about submodule behaviors when I supported GSI/EnKF to the community even though GSI only contains 1 or 2 submodules, :)

The external management system will require a one-time setup cost. But once it is established, general users can do normal simple git operations without additional effort. Since the rrfs-workflow has already developed an external management system, the one-time setup cost may be minimized.

On the other hand, RDASApp borrows many parts from GDASApp, So I am hesitant to advocate moving away from submodules  for RDASApp.

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  I believe if the benefit is obvious and significant,  rdasapp could of course evolve with differences from GDAsapp.  But use of submodule by gdasapp itself is an evidence of its efficiency/benefits. So change of it needs more evidences of the benefits.   For being now ( rdas is at the developing mode),  the control for submodules by the hash is not as important as when some version of the whole system is to be released and some freezing is needed, I think it should always be recommended to use the current heads for all submodules (by running " git submodule update --remote") .  
Another option is to enhance the current submodule based rdasapp by adding some extra setup /tools as discussed in this discussion you initiated.

**Comment by guoqing-noaa** [comment]
Thank @TingLei-NOAA for discussions. You bring up another topic.  Currently, the clone and build instructions in the wiki suggest using the latest commit for each submodule.  I have concerns about this.  

If we work only on one repository, it is desirable to use the latest commit. However, RDASApp involves 17 submodules. It is not guaranteed that the latest commits from all submodules will always coordinate with each other. It is prone to glitches. 

Also, the latest commits are moving targets. If all developers use the latest commits for all submodules, we will refer to different snapshots of RDASApp and not talk about the same thing.  If we want to repeat a previous test, we also don't know what commits of submodules to repeat.

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  This topic had been discussed much and will, I believe, continue to be discussed further and more broadly. 
The main argument is that , since we would directly work with and push back our developments to those submodules, it would "normally" be the better practice to always start our work by clone/create the rdasapp with the current heads for all submodules unless there are specific reasons again this. Maybe, it is enough just for a few  developers/like rdasapp code managers to keep tracking of some hash of rdasapp for possible use cases for those snapshots.

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA Tests/experiments with snapshots do not prevent working on submodules and contributing back.  Using rrfs-workflow as an example, collaborators always discuss experiments, issues, etc based on a given snapshot and developers still contribute back to the submodules (GSI, UPP, ufs_model, utils, etc) without any problems. I did not see any roadblocks here. Or did I miss something?

**Comment by hu5970** [comment]
@guoqing-noaa @TingLei-NOAA Thanks for good discussions. My  two cents:
1) we will make a code management policy for RDASApp soon. We do need a clear path to maintain stable version of the RDASApp and at the same time, following the authoritative repository and contribute back.
2) 16 submodules are a lot to track. We usually only work on a few. We can ignore some and track some. Let's figure out which one we should track and which one we should ignore.

**Comment by TingLei-NOAA** [comment]
> @TingLei-NOAA Tests/experiments with snapshots do not prevent working on submodules and contributing back. Using rrfs-workflow as an example, collaborators always discuss experiments, issues, etc based on a given snapshot and developers still contribute back to the submodules (GSI, UPP, ufs_model, utils, etc) without any problems. I did not see any roadblocks here. Or did I miss something?

I think the key is which way is more efficient and it is a difficult to conclude now and let 's keep discussion on this .

**Comment by guoqing-noaa** [comment]
> I think the key is which way is more efficient and it is a difficult to conclude now and let 's keep discussion on this .

@TingLei-NOAA Good question. I think each person may have a different view about what is more efficient, :) 

However, for collaboration purposes, as @hu5970 mentioned, we need to be on the same page (i.e. using a snapshot instead of a moving target) when we talk about tests/issues/results.

**Comment by TingLei-NOAA** [comment]
> > I think the key is which way is more efficient and it is a difficult to conclude now and let 's keep discussion on this .
> 
> @TingLei-NOAA Good question. I think each person may have a different view about what is more efficient, :)
> 
> However, for collaboration purposes, as @hu5970 mentioned, we need to be on the same page (i.e. using a snapshot instead of a moving target) when we talk about tests/issues/results.

That is another interesting point.  When we use submodule and directly push back any developments with those submodules to their current heads,  will "the same page" mean the  "then current heads" of those submodules? Maybe a balanced way is as @hu5970  , to put the submodules to two categories, one of which will be introduced with more control by hash numbers and the other will be given the free pass (namely always use their heads).

**Comment by guoqing-noaa** [comment]
>will "the same page" mean the "then current heads" of those submodules? 

I am afraid it is a no. Different users at different times will check out different commits for submodules, i.e. different "current heads", and hence we are not on the same page and we may not refer to the same thing when we talk about tests/issues/results.

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  Even for the same person,  checking out the heads on different time will also mean  different versions. But that doesn't mean he/she should stick to the original version to keep himself "on the same page".  That is not the way develops work on the same system.    It is not so simple to equal "the same page" to "same version" started from.  So, as I said, let us keep discussions while it is difficult (to have a simple conclusion).

**Comment by guoqing-noaa** [comment]
> Even for the same person, checking out the heads on different time will also mean different versions. 

That's why we don't want to check out current heads for each submodules automatically.  We will need to collaborate on a stable version (a snapshot) and we can repeat results even a few days/weeks later.

>But that doesn't mean he/she should stick to the original version to keep himself "on the same page". 

 Working on snapshots does not mean we stick to one old version. The submodules can evolve without any problems. Do you see any roadblocks preventing us from updating submodules? My point is that we need to update submodules and track them in RDASApp, not by users running `git submodule update --init --remote` command which is not manageable for collaborations. That means each commit in RDASApp is associated and only associated with a given set of submodule commits (NOT volatile "current head"). If we want to use new versions for some submodules, we need to update them in RDASApp so other collaborators are aware of the update.

**Comment by hu5970** [comment]
@TingLei-NOAA @guoqing-noaa  very good discussion. It would be a little easier if we can have a tag-up to chat on this topics.  I will find a time. Thanks, Ming

**Comment by guoqing-noaa** [comment]
Shun, Ming, Ting, and I had a meeting this morning and reached an agreement.
We will live with submodules but it is good to add "`ignore=dirty"` to each submodule.

@SamuelDegelia-NOAA  Could you go ahead to create a PR to update this? Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
Will do! Do we want to ignore all submodules or leave tracking on for some (as proposed by Ming in an earlier reply)?

**Comment by guoqing-noaa** [comment]
> Will do! Do we want to ignore all submodules or leave tracking on for some (as proposed by Ming in an earlier reply)?

For now, ignore all submodules. If we find any needs, we can always change later. Thanks!

**Comment by guoqing-noaa** [comment]
Close this issue. Thanks all for discussions and contributions!
