### ISSUE TITLE
e-folding radius vs cutoff radius

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#67]
Thank @hu5970 for bringing this up in our small group meeting. We need to clarify what "radius" it is when we talk about decorrelation scale and localization scale.

For static BE, it is the e-folding radius for decorrelation scales

For ensemble BE, it will depend on the localization method, right? For example, Gaussian localization may use the e-folding radius while Gaspari-Cohn localization may use the cutoff radius?

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa   Good question.  I believe that for all bump-based calculation, whether for  ensemble localization or static B), the Gaspari-cohn function is used. In this context , the "length scale" for support function is the cutoff radius for Gaspari-cohn function.  However, when using the gsi-recursive filter as implemented in  GSIBEC of saber (currently only available for global ), additional caution is needed.

**Comment by guoqing-noaa** [comment]
Thanks, @TingLei-NOAA. I did not know that BUMP also uses the Gaspari-Cohn function for static BE. So if static BE is involved, when we compare GSI vs JEDI, we will need to pay attention to the length scales which will be different in GSI and JEDI unless JEDI  uses GSIBEC.

**Comment by guoqing-noaa** [comment]
Adapted from https://journals.ametsoc.org/view/journals/mwre/141/11/mwr-d-12-00141.1.xml:

`The E-folding distances equivalent to 1600 km and 1.1 scale height (natural log of pressure is equal to 1.1) cutoff distances in the [Gaspari and Cohn (1999)](https://journals.ametsoc.org/view/journals/mwre/141/11/mwr-d-12-00141.1.xml#bib15) localization function were adopted for the horizontal and vertical localizations, respectively, in the current study.`

So it looks like GSI uses e-folding radius for horizontal localization while cut-off radius for vertical localization.

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  I think in gsi , the same lenghscale is used for the horizontal and vertical directions, but different  GSI variational app (gsi.x) uses e-folding, while GSI enk uses cut-off radius. 
That is there is a conversion between the length scales by GSI::gsi.x and GSI::enkf.x as described in the doc for init_rf_z in hybrid_ensemble_isotropic.F90 
```
   2010-04-06  parrish - add 2nd option for units of vertical localization:
   ..........
!                             For the current s_ens_v > 0, the measure is vertical grid units.
!                             s_ens_v = 20 and s_ens_v = -0.44 are roughly comparable, and
!                             connection of .44 is .44 = (sqrt(.15)/sqrt(2))*1.6, where 1.6 is the value used
!                             by Jeff Whitaker for his distance in which the Gaspari-Cohn function 1st = 0.
````
while it is for vertical localization here.

**Comment by TingLei-NOAA** [comment]
From another point of view, when recursive filter is used , e-folding scale or the scale for the original gaussian function is used, while explicit function like gaspari-cohn function is used, the cut-off scale is used.

**Comment by XuLu-NOAA** [comment]
@guoqing-noaa 
If you are interested, eq. (4) and the corresponding text in the following paper provides the conversion between GSI, EnKF, and GC e-folding distance:
https://journals.ametsoc.org/view/journals/mwre/142/10/mwr-d-13-00242.1.xml?tab_body=fulltext-display
I'm wondering when you say BUMP, do you mean the NICAS?

**Comment by guoqing-noaa** [comment]
Thanks @TingLei-NOAA and @XuLu-NOAA for inputs! 
I just checked this source code (I should have done this earlier,:) )
```
!     s_ens_h - horizontal localization correlation length of Gaussian exp(-0.5*(r/L)**2)
!               (units of km), default = 2828.0
!     s_ens_v - vertical localization correlation length of Gaussian exp(-0.5*(r/L)**2)
```
So it is confirmed that GSI uses the Gaussian form of ensemble localization both horizontally and vertically.

That's why we see different effective length scales in the single observation increment fields between GSI and JEDI when  @spanNOAA conducted single ob METAR obs test.

**Comment by guoqing-noaa** [comment]
Thanks @XuLu-NOAA for the equation:

![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/d29d721f-5740-40b9-ad46-2887f2af1424)

So for 110km radius in GSI, it should be 401.7 km radius in JEDI

**Comment by XuLu-NOAA** [comment]
Hi @guoqing-noaa 
In my understanding, 110-km in GSI should be equivalent to 401-km in cut-off radii from EnKF (Or what we actually see in increments), but 311-km in e-folding for JEDI.
![image](https://github.com/NOAA-EMC/RDASApp/assets/26603014/e9c61749-44a7-4ce9-bf0b-864e67ba9f8f)

**Comment by guoqing-noaa** [comment]
Thanks, @XuLu-NOAA !  To my understanding, at the moment, JEDI can only specify cutoff radius. 
Are you aware of a way to specify e-folding radius in JEDI?

**Comment by XuLu-NOAA** [comment]
@guoqing-noaa This is actually something I'm trying to figure out. I'm testing the localization through BUMP-NICAS, it looks to me that the configurations in JEDI is in e-folding (or Gaspari-Cohn radii), not cutoff. 
![image](https://github.com/NOAA-EMC/RDASApp/assets/26603014/78ea1c27-161b-4146-9f63-61d4ad21c61f)
But I'm seeing some strange patterns when I set small values in horizontal and my vertical length-scale is somehow only affected by my horizontal configurations. So I'm wondering to see if you or @TingLei-NOAA  have more experiences with those configurations. Are those dotted patterns with "small" (100-km) localization normal in JEDI? Or do you have any idea how should I check those output? Thanks!
![image](https://github.com/NOAA-EMC/RDASApp/assets/26603014/c4426a36-cf13-4cca-8110-b5073729abb7)

**Comment by XuLu-NOAA** [comment]
This is a single ob at 25N, 80W with 10mem ensemble B, no static B involved

**Comment by XuLu-NOAA** [comment]
And I found in this wiki-page, it claims GC radii for horizontal configurations
https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/saber/BUMP_saber_blocks.html#nicas-calibration

**Comment by TingLei-NOAA** [comment]
@XuLu-NOAA  Thanks a lot for your contribution on this topic.  Definitely, we need some further off-line discussion on the accurate use of the terms and relationships among them.

**Comment by spanNOAA** [comment]
> we

@XuLu-NOAA What is the approximate resolution of your model? Have you observed any reduction in the effective horizontal resolution of NICAS?

**Comment by spanNOAA** [comment]
> @guoqing-noaa This is actually something I'm trying to figure out. I'm testing the localization through BUMP-NICAS, it looks to me that the configurations in JEDI is in e-folding (or Gaspari-Cohn radii), not cutoff. ![image](https://private-user-images.githubusercontent.com/26603014/340470875-78ea1c27-161b-4146-9f63-61d4ad21c61f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDQwNTEsIm5iZiI6MTcxODc0Mzc1MSwicGF0aCI6Ii8yNjYwMzAxNC8zNDA0NzA4NzUtNzhlYTFjMjctMTYxYi00MTQ2LTlmNjMtNjFkNGFkMjFjNjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDIwNDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNzY2Y2MzN2UzODcyZDA1NGY0NGZhMWYxZDJmZGI0MDIxNjE3OWZkNmM0OGMxNzA0ZDZjODJlOGIwNDUzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.beT-GI3i9xDloawRvD4oEIgAK70yVrYFU-ZHcRhyJBk) But I'm seeing some strange patterns when I set small values in horizontal and my vertical length-scale is somehow only affected by my horizontal configurations. So I'm wondering to see if you or @TingLei-NOAA have more experiences with those configurations. Are those dotted patterns with "small" (100-km) localization normal in JEDI? Or do you have any idea how should I check those output? Thanks! ![image](https://private-user-images.githubusercontent.com/26603014/340471149-c4426a36-cf13-4cca-8110-b5073729abb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDQwNTEsIm5iZiI6MTcxODc0Mzc1MSwicGF0aCI6Ii8yNjYwMzAxNC8zNDA0NzExNDktYzQ0MjZhMzYtY2YxMy00Y2NhLTgxMTAtYjUwNzM3MjlhYmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDIwNDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMWMwODlhMDg5MGYzNzllZDBjZTAyZTdjYWViZDEyZGJkYmNmYmNkODQ3YjVjZmJmMDI5ZTEzMTYwNjIxMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nJb8jyhyA-S-MyTbtoEEwLKgsM2Uu0U1pGDEA6ye2J8)

@XuLu-NOAA What is the approximate resolution of your model? Have you observed any reduction in the effective horizontal resolution of NICAS?

**Comment by spanNOAA** [comment]
In my single observation experiment using a 110km radius [#46](https://github.com/NOAA-EMC/RDASApp/issues/46#issuecomment-2176958985) , I did not observe any cluttered patterns in the analysis increment.

**Comment by XuLu-NOAA** [comment]
> In my single observation experiment using a 110km radius #46 , I did not observe any cluttered patterns in the analysis increment.

Thanks, @spanNOAA , your results look reasonable to me. I'm using a ~3-km model grid spacing and I've tried resolution=30 for the BUMP NICAS. Would you mind letting me to take a look at your bump yaml file?

**Comment by spanNOAA** [comment]
Yes, you can find it on Orion or Hercules: /work/noaa/wrfruc/span/jedi_summer_retro/jedi_prepbufr_analysis/2023061012_singleobs_bgen/bump_nicas1/d-bump.yaml. 

From my understanding, the resolution and lengthscale determine the number of horizontal grid points used in NICAS. Due to computational costs increasing with more grid points, NICAS sets an upper limit on the number of horizontal grid points by default to avoid excessive computational expense. If the estimated horizontal grid size based on the specified resolution and lengthscales exceeds the maximum allowed, NICAS automatically reduces the effective NICAS resolution. Therefore, I had to specify a maximum horizontal grid size of 120k in my YAML configuration for a model resolution of approximately 13 km, horizontal lengthscales of 110 km and NICAS resolution of 8. You can checkout your effective NICAS resolution by searching for "horizontal support radius", getting results such as this:
![Screen Shot 2024-06-18 at 19 15 41](https://github.com/NOAA-EMC/RDASApp/assets/142531472/2fde7150-4916-44ce-b3cd-707af4f66017)

While this might not directly relate to your issue, I wanted to share this information for your reference.

**Comment by guoqing-noaa** [comment]
Thank @spanNOAA for a new set of single ob experiments. He posted results in issue #46 . I reposted here for convenience: 

![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/db73945b-194b-4ae9-83a8-bfec1fa48283)
![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/a7495344-61e9-4347-89be-46bb7f9efcfb)
GSI h110km: Number of values falling between 0.050857356826984675 (maxval/e) and 0.13824462890625 (maxval): 12
JEDI h110km: Number of values falling between 0.05738280633564391 and 0.1559826397281654: 6
JEDI h311km: Number of values falling between 0.05985338604609267 and 0.1626983716608379: 9
JEDI h401km: Number of values falling between 0.05958699176913942 and 0.16197423693859037: 11


### Discussion: 
The last 4 lines in the above are to compute the e-folding radius based on increments along the same horizontal line through the increment center.
So if we want to pair JEDI with GSI based on the same e-folding radius,  GSI 110km matches JEDI 401km
if we want to pair JEDI with GSI based on the same cut-off radius,  GSI 110km matches JEDI 311 km
I would vote to pair based on the same e-folding radius. Feel free to chime in about your thoughts. Thanks!

**Comment by guoqing-noaa** [comment]
@spanNOAA how do you draw the horizontal line? Is it something like this:

![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/81e2268f-f74a-4ee3-bb1f-493946bc8ab4)

**Comment by guoqing-noaa** [comment]
@XuLu-NOAA In most situations people will use the "cutoff" radius when working with the Gaspari-Cohn function as it is more straightforward unless some extreme situations happen.  JEDI would follow this rule as well. 

A few examples:
1. https://github.com/ecosme38/Data-Assimilation-Notebooks/blob/master/Illustrate-Gaspari-Cohn-function-and-covariance-localization.ipynb
If you scroll down, you will find "`dcut = 4.                            # Correlation length scale`"

2. In this paper: 
https://journals.ametsoc.org/view/journals/mwre/141/11/mwr-d-13-00039.1.xml?rskey=aVm4oX&result=12
![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/b1d34ace-8208-4818-a819-9dfccb6259e1)
You can see a cutoff radius is used.

**Comment by XuLu-NOAA** [comment]
> Yes, you can find it on Orion or Hercules: /work/noaa/wrfruc/span/jedi_summer_retro/jedi_prepbufr_analysis/2023061012_singleobs_bgen/bump_nicas1/d-bump.yaml.
> 
> From my understanding, the resolution and lengthscale determine the number of horizontal grid points used in NICAS. Due to computational costs increasing with more grid points, NICAS sets an upper limit on the number of horizontal grid points by default to avoid excessive computational expense. If the estimated horizontal grid size based on the specified resolution and lengthscales exceeds the maximum allowed, NICAS automatically reduces the effective NICAS resolution. Therefore, I had to specify a maximum horizontal grid size of 120k in my YAML configuration for a model resolution of approximately 13 km, horizontal lengthscales of 110 km and NICAS resolution of 8. You can checkout your effective NICAS resolution by searching for "horizontal support radius", getting results such as this: ![Screen Shot 2024-06-18 at 19 15 41](https://private-user-images.githubusercontent.com/142531472/340880295-2fde7150-4916-44ce-b3cd-707af4f66017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTc1NjcsIm5iZiI6MTcxODc5NzI2NywicGF0aCI6Ii8xNDI1MzE0NzIvMzQwODgwMjk1LTJmZGU3MTUwLTQ5MTYtNDRjZS1iM2NkLTcwN2FmNGY2NjAxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMTQxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWFlYTI4NTJjZTEyNDU3NGIyMmEzMmNmNTM0OTZlZjA4NGQxODllM2VkMmExNjY0OTc0NzdjOGEzNjM5Zjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ErkFPXEiuXpSUeWKs3Oq2daMjgNsYVBvEB14bRqPeVo)
> 
> While this might not directly relate to your issue, I wanted to share this information for your reference.

@spanNOAA Thanks for your info, this is very helpful. Currently, my support radius is 788k, and the effective resolution is only 4.14. I'll test with the maximum grid size. Hopefully, it would address my concern.

**Comment by XuLu-NOAA** [comment]
> @XuLu-NOAA In most situations people will use the "cutoff" radius when working with the Gaspari-Cohn function as it is more straightforward unless some extreme situations happen. JEDI would follow this rule as well.
> 
> A few examples:
> 
> 1. https://github.com/ecosme38/Data-Assimilation-Notebooks/blob/master/Illustrate-Gaspari-Cohn-function-and-covariance-localization.ipynb
>    If you scroll down, you will find "`dcut = 4.                            # Correlation length scale`"
> 2. In this paper:
>    https://journals.ametsoc.org/view/journals/mwre/141/11/mwr-d-13-00039.1.xml?rskey=aVm4oX&result=12
>    ![image](https://private-user-images.githubusercontent.com/51679803/340928937-b1d34ace-8208-4818-a819-9dfccb6259e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTc1NjcsIm5iZiI6MTcxODc5NzI2NywicGF0aCI6Ii81MTY3OTgwMy8zNDA5Mjg5MzctYjFkMzRhY2UtODIwOC00ODE4LWE4MTktOWRmY2NiNjI1OWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExNDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNWI4YzZhOGFmOTU0NjIyZjhlN2Q1MzU3MjE5YTA4ZDhjOWY5ZjgwMjc0Zjc0MjZiOTNiM2MzZGE4NWIwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U95n-4R4SZwEy1fEDdpPNpjuvuYKaMA2vHaXVorb-Fs)
>    You can see a cutoff radius is used.

@guoqing-noaa I see, thanks for your clarification.

**Comment by guoqing-noaa** [comment]
Thanks all for the discussion on this important topic.
It is agreed and confirmed that JEDI uses a cutoff radius while GSI (excluding the EnKF part) uses an e-folding radius.
We should use this equation:

![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/9fe78b4d-c355-41c0-ae14-49bd4c40f1fb)

to convert GSI's current radius values to comparable JEDI radius values.
`For example, 110km radius in GSI should be 401.7 km radius in JEDI`

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa Do you know if this equation also holds for converting vertical localization between GSI and JEDI if using ln(p) units?

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa Do you know if this equation also holds for converting vertical localization between GSI and JEDI if using ln(p) units?

Yes, I would think so. It will be good to confirm it using single ob tests.

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa Thank you!

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa I think the conversion works pretty well. Here is a comparison of a single surface ob test between GSI and MPAS-JEDI. The increment structure/magnitude is different due to different backgrounds, but overall both increments go to zero at around the same level. 

![Screenshot 2024-12-17 003340](https://github.com/user-attachments/assets/9999c5d8-9ee4-42f2-a718-8765df9229fb)

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks for confirming this! Great figures!
