### ISSUE TITLE
Add GSL developers to this repo

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#69]
I found that quite a few GSL developers may not be added to this repo yet.

For example, I cannot @spanNOAA, @junjun-NOAA, @chunhuazhou, etc directly.

**Comment by SamuelDegelia-NOAA** [comment]
@CoryMartin-NOAA could you add these developers?

**Comment by guoqing-noaa** [comment]
Thanks @SamuelDegelia-NOAA @CoryMartin-NOAA 
Let's assemble a list of GSL developers to be added to this repo. We should have a few more. 
FYI @hu5970

**Comment by CoryMartin-NOAA** [comment]
Give me or @ShunLiu-NOAA a list and we should be able to add them as collaborators with write access

**Comment by ShunLiu-NOAA** [comment]
@hu5970 should be able to add developers from GSL to the team as well. I will add Sijie and Chunhua as collaborators first.

**Comment by guoqing-noaa** [comment]
Thanks, @ShunLiu-NOAA and @CoryMartin-NOAA 

Shun, could you add @Junjun-NOAA as well?

**Comment by ShunLiu-NOAA** [comment]
@Junjun-NOAA is added to the list.

**Comment by guoqing-noaa** [comment]
Thanks, Shun!

**Comment by guoqing-noaa** [comment]
@ShunLiu-NOAA It looks like @chunhuazhou has not been added yet?

**Comment by guoqing-noaa** [comment]
@ShunLiu-NOAA The invitation has expired. Could you add her again?  @chunhuazhou
