### ISSUE TITLE
Add 13km RRFS CONUS domain test case for RDAS 3DEnVar test

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [NOAA-EMC/RDASApp#7]
1. Create a test case for RDASApp with a background of RRFS 13km COUNS domain.
2. Stage RRFS background on hera and orion.

**Comment by TingLei-NOAA** [comment]
Update : some current plans on how to add this kind of RRFS tests to RDAS.   One main problem is the data for this kind of tests are too large to be put on github and, hence, most of them would be locally put on , for being now, hera and orion.   The corresponding question is how to "organize" such tests into RDAS through cmake management .   The current plan is to,basically, follow the example of the incorporation of the global work into GDASapp ( controlled by the WORKFLOW_BUILD option initiated logics).
I will start to work from my fork of  RDAS, following PR processes with EMC GSI. 
This issue will facilitate our discussion before any formal PR begin.
