### ISSUE TITLE
RRFS CTest failed on Hera

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#74]
@EricJames-NOAA found that RRFS CTest failed on Hera:
/scratch2/BMC/wrfruc/ejames/RDASApp/build/Testing/Temporary/LastTest.log

I tried on one of my previous build today and it also failed. 
Something changed on Hera?

I am now starting from scratch to test this.
It will be good that if anyone can also try it on Hera at the same time.

**Comment by SamuelDegelia-NOAA** [comment]
I just ran the CTest on Hera using a build from last Friday and it was successful. Looking at @EricJames-NOAA log file, there is no obvious error message other than a segmentation fault at the start of OOPS. Is Eric's error the same as yours?

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks for checking. I also got segmentation fault. But the test output is differnt.

`/scratch1/BMC/wrfruc/gge/RDASApp/build/Testing/Temporary/LastTest.log`

**Comment by guoqing-noaa** [comment]
I think I may find the reason. I started from a clean clone and repeated every step in the instruction (https://github.com/NOAA-EMC/RDASApp/blob/develop/docs/build_and_test.md) and all CTests passed.

@EricJames-NOAA You may forget step 3.1 "load modules". Could you try to load modules again and run ctests? Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
Okay, glad it is working now.

**Comment by guoqing-noaa** [comment]
Close this issue. The build_and_test.md has been updated accordingly.
