### ISSUE TITLE
Ioda-converters YAML for EFCLAM data

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [NOAA-EMC/RDASApp#76]
Write an example YAML for the EFCLAM 3[D]-RTMA/RRFS data that converts a BUFR file to an IODA file using the bufr2ioda.x for the following subset(s):

| NC012160 | A61109 | M TYPE 012-160  U.WI GOES Imager Effective Cld Amt data  |

- [x]  Extract the BUFR table, queries, and important Mnemonics information
- [x]  Use this YAML to convert into an IODA-formatted netCDF file
- [ ]  Ioda obs validation using ioda-validate.x
- [x]  Perform validation for the observations using the input BUFR and output IODA file
- [ ]  Add output(s) to the testoutput directory
- [ ]  Add tests to the CMakeLists.txt files
- [ ]  Have the tests pass

# Requirements
All important mnemonics required by the [3D]-RTMA/RRFS users need to be known.

# Acceptance Criteria
It will be finished when all files have been checked and tests have passed.

# Dependencies
The bufr2ioda.x

**Comment by PraveenKumar-NOAA** [comment]
Performed validation of the ioda-obs in the output ioda file generated using the bufr2ioda-x and following results were obtained:

Validation of the output IODA results, obtained using the efclam ioda-converters YAML and bufr2ioda.x, is performed for the following two observations:

**cloudAmount (ECAS)
BUFR plot:**
![bufr_efclam_cloudAmount](https://github.com/NOAA-EMC/RDASApp/assets/63739712/a6cfe398-6f46-4618-bb3d-ebe7d4e82392)


**IODA plot: 
![efclam-ioda_cloudAmount](https://github.com/NOAA-EMC/RDASApp/assets/63739712/693fafa3-12dd-45f8-bff7-b652d83eae9f)


cloudCoverAmount (ECAM)
BUFR plot:
![bufr_efclam_cloudCoverTotal](https://github.com/NOAA-EMC/RDASApp/assets/63739712/dd82d6a5-0b9e-43ac-aa10-6b215b272a39)


IODA plot:**
![efclam-ioda_cloudCoverTotal](https://github.com/NOAA-EMC/RDASApp/assets/63739712/95af3a07-b810-427d-bd87-bc34592490f9)

**Comment by guoqing-noaa** [comment]
Sorry that this is the first time I heard of EFCLA. What does it stand for?
Are they the NASA LaRC cloud data? Thanks!

**Comment by PraveenKumar-NOAA** [comment]
@guoqing-noaa EFCLAM/ NC012160 is GOES imager effective cloud amount data (U.Wisc.)

**Comment by ShunLiu-NOAA** [comment]
@ManuelPondeca-NOAA Could you confirm this observation are used in RTMA?

**Comment by MatthewMorris-NOAA** [comment]
> @ManuelPondeca-NOAA Could you confirm this observation are used in RTMA?

@ShunLiu-NOAA Yes, these GOES Imager obs are used in the operational RTMA/URMA, and we plan to use them going forward to 3D-RTMA.

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA Do you know what the difference is between the ECAS and ECAM data? If not, I can reach out to Jim Nelson at UWisc CIMSS for clarification.

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA please find below the description for these from the bufr table: 
| ECAS     | 020202 | SATELLITE MEASURED EFFECTIVE CLOUD AMOUNT AT CENTER FOV  |
| ECAM    | 020203 | SATELLITE MEASURED EFFECTIVE CLOUD AMOUNT AVG MULT. FOV  |

both are in % unit. For further clarification, you can contact Jim Nelson.

**Comment by MatthewMorris-NOAA** [comment]
Thank you, Praveen, for this information. For your awareness, I'm sharing the following information contained in an old email from Jim Nelson. This suggests that the ECAM data is smoothed relative to ECAS. At any rate, the figure comparisons look good.

"...show cloud emissivity valid for a specific GOES Field of View (FOV, nominally 4 x 4 km at the satellite subpoint (0N,137W)).  This data comes directly from the CLAVR-x software being run here at CIMSS.  The GOES Imager Sky Cover software is not doing any further processing of this data, prior to writing it to the GOES-17 *TXT files NCEP pulls from the SSEC anonymous ftp server ([ftp.ssec.wisc.edu](ftp://ftp.ssec.wisc.edu/)).  Note especially that this data occupies field #6 (of 10 fields, total) within each line of text within the GOES-17 *TXT files.   Note also that this ties in directly as one of the data values that is written to a BUFR file prior to input to the RTMA (and presumably also the URMA)." --> This appears to correspond to the ECAS data.

"...show a computed average cloud emissivity valid for a specific GOES Field of View (FOV).   This average emissivity is computed from a matrix of FOVs that surround (and include) the FOV being processed.  The X and Y dimensions of the matrix are determined by computing how many FOVs are required to traverse a distance of 25 kilometers north, south, east and west of the FOV being processed.  Depending on the location of the FOV being processed relative to the subpoint of the GOES satellite, the number of FOVs is not always equal in all 4 directions.   Furthermore, as you get further from the satellite subpoint, a given GOES FOV covers a larger portion of the earth’s surface, meaning you don’t need as many FOVs to traverse the 25 kilometer distance.  In any case, each FOV contained within the computed X by Y matrix is checked to see if it falls within a 25 kilometer great circle distance of the FOV being processed.  If so, the cloud emissivity valid for that FOV is added to all the other FOV cloud emissivities that also lie within the 25 kilometer great circle distance, and a final simple average cloud emissivity is computed and written to field #5 (of 10 fields, total) within each line of text within the GOES-17 *TXT files.   Note also that this ties in directly as one of the data values that is written to a BUFR file prior to input to the RTMA (and presumably also the URMA)." --> This appears to correspond to the ECAM data.
