### ISSUE TITLE
Need to update mpas and mpasjedi in RDASApp

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#87]
We tried using [Chunhua's MPAS case](https://github.com/NOAA-EMC/RDASApp/issues/41) to create a CONUS_12km MPASJEDI case. 
The test directory can be found at:
`/scratch1/BMC/wrfruc/gge/RDASApp/expr/jedi-assim_test/rrfs-data_mpasjedi_2024052621`

We found that Chunhua used the GSL MPAS versions with GSL new physics and this cannot be handled by the current MPASJEDI and MPAS submodules in RDASApp. 

We discussed this with Tao Sun from the NCAR MPASJEDI team.  Per Tao's information, it is best to use the latest commit in the [`feature/MPAS-Model_v8.1`](https://github.com/JCSDA-internal/mpas-jedi/commits/feature/MPAS-Model_v8.1/) branch of mpas-jedi and commits after May 21, 2024 of [the develop branch of MPAS-Model](https://github.com/MPAS-Dev/MPAS-Model/commits/develop/?before=7070294994eb6e53e9133f15711cf0285fc70437+105) which contain necessary codes for using new physics.

So, if RDASAPP wants to use GSL's new physics, [GSL's MPAS-Model](https://github.com/NOAA-GSL/MPAS-Model/commits/gsl/develop/) needs to include the above-mentioned commits from the community MPAS-Model. This will happen but not in the near future

Thank @Junjun-NOAA, @spanNOAA, @xyzemc and @TingLei-NOAA for help and discussion in this process.
Tag @ShunLiu-NOAA @hu5970

**Comment by guoqing-noaa** [comment]
For reference, here is Xiaoyan's MPAS-model used to generate the 2022052619 mpasjedi case in current RDASApp:

```
/scratch2/NCEPDEV/fv3-cam/Xiaoyan.Zhang/noscrub/MPAS/MPAS-Model.befRocky8

Merge: 1d6ec7c21 2bfdc6ba3
Author: Michael Duda <duda@ucar.edu>
Date:   Thu Jul 6 23:46:22 2023 +0000

    Merge branch 'hotfix-v8.0.1'
```

And Ting's script to make it a mpasjedi case:
`/scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-mpas-bundle/rdas-mpas-tests/CONUS_15km_da/prep_denvar_reg_xzhang.csh`

**Comment by ShunLiu-NOAA** [comment]
@guoqing-noaa Will [feature/MPAS-Model_v8.1](https://github.com/JCSDA-internal/mpas-jedi/commits/feature/MPAS-Model_v8.1/) allow us to run Chunhua's new test case with GSL's new physics? If yes, how long will it take to merge this feature branch to "develop"?

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa Will [feature/MPAS-Model_v8.1](https://github.com/JCSDA-internal/mpas-jedi/commits/feature/MPAS-Model_v8.1/) allow us to run Chunhua's new test case with GSL's new physics? If yes, how long will it take to merge this feature branch to "develop"?

It opens the possibility to use new physics if we add new physics based on the May 21st commit. 
However, GSL's physics has not been committed to the community nor does GSL's MPAS_MODEL contain those important commits.

@hu5970 and I will talk with Joe Olson next Monday to see what the plan going forward.

**Comment by ShunLiu-NOAA** [comment]
I don't think GSL new physics is the most important factor for RDAS test case at the moment. Is it possible to have MPAS test case that matches MPAS-JEDI _develop_ ?

**Comment by guoqing-noaa** [comment]
@ShunLiu-NOAA I agree. 

@Junjun-NOAA is working on generating a 2024052700z case using the MPAS_MODEL version similar to what @xyzemc has used.

**Comment by ShunLiu-NOAA** [comment]
Thank you!

**Comment by guoqing-noaa** [comment]
For reference, this is a reply from Joe Olson:
>We are anticipating a v8.2 release very soon, probably next week. That should include all the commits in the develop branch. We can sync with that version when it's available.

**Comment by guoqing-noaa** [comment]
Since we figured out a way to run Chunhua's mpas case, updating the mpas and mpasjedi submodules is no longer an urgent task.

But if we want to use the "mpasout" functionality (similar to wrfout for WRF where we don't do DA on WRF restart files) and to couple well with the new physics development, it is still desirable to make the mentioned updates.

**Comment by guoqing-noaa** [comment]
FYI:

![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/47fc0986-6bfa-4d13-948f-03787760e862)
