### ISSUE TITLE
mpasjedi crashed for the new 2024052700 case

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#89]
@Junjun-NOAA and I have been creating a new `mpasjedi_2024052700 `case following @chunhuazhou setting but using the community physics.

We have successfully created the bump localization files.

But mpasjedi crashed when running a pure 3DEnVar single sonde observation case (similar as in issue #83 )

The run directory is at:
`/scratch1/BMC/wrfruc/gge/RDASApp/expr/jedi-assim_test/rrfs-data_mpasjedi_2024052700`

We found that `mpasjedi_2022052619 `case modified all ensemble restart files with a `dchg.py` program. Is this key to successfully running a mpasjedi case? If yes, why would we need to make this change?

Any suggestions? @TingLei-NOAA @xyzemc @SamuelDegelia-NOAA 

Thanks!

**Comment by guoqing-noaa** [comment]
I ran dchg.py on each restart file but mpasjedi still crashed.

```
  0: ==== backtrace (tid: 799561) ====
  0:  0 0x00000000000534e9 ucs_debug_print_backtrace()  ???:0
  0:  1 0x0000000000012cf0 __funlockfile()  :0
  0:  2 0x0000000000a473b0 vert_interp_mod_mp_vert_interp_weights_()  /scratch1/BMC/wrfruc/gge/myRDASApp/bundle/ufo/src/ufo/utils/vert_interp.F90:73
  0:  3 0x0000000000a9a828 ufo_vertinterp_mod_mp_vertinterp_simobs__()  /scratch1/BMC/wrfruc/gge/myRDASApp/bundle/ufo/src/ufo/operators/vertinterp/ufo_vertinterp_mod.F90:341
  0:  4 0x0000000000a96567 ufo_vertinterp_simobs_f90()  /scratch1/BMC/wrfruc/gge/myRDASApp/bundle/ufo/src/ufo/operators/vertinterp/ObsVertInterp.interface.F90:98
  0:  5 0x0000000000a8cc3b ufo::ObsVertInterp::simulateObs()  /scratch1/BMC/wrfruc/gge/myRDASApp/bundle/ufo/src/ufo/operators/vertinterp/ObsVertInterp.cc:60
  0:  6 0x0000000000a8cc3b ufo::ObsVertInterp::simulateObs()  /scratch1/BMC/wrfruc/gge/myRDASApp/bundle/ufo/src/ufo/operators/vertinterp/ObsVertInterp.cc:63
  0:  7 0x000000000042e404 ufo::ObsOperator::simulateObs()  /scratch1/BMC/wrfruc/gge/myRDASApp/bundle/ufo/src/ufo/ObsOperator.cc:57
  0:  8 0x000000000042e404 ufo::ObsOperator::simulateObs()  /scratch1/BMC/wrfruc/gge/myRDASApp/bundle/ufo/src/ufo/ObsOperator.cc:58
```

**Comment by SamuelDegelia-NOAA** [comment]
The error backtrace points to an issue with the VertInterp obs operator in UFO, likely with an indexing issue when accessing the background pressure. I had a look at your input data and compared it to our `2022052619` case data. It looks like your data in `rrfs-data_mpasjedi_2024052700/Data/bkg/restart.2024-05-27_00.00.00.nc` is missing some pressure information, in particular the `pressure_p` and `pressure_base` variables. I cannot confirm if that is the cause of this issue but it is worth looking into.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks for checking on this!
Sorry that I made a few hypotheses and then did a few experiments but forgot to restore the original data. 
Now I restored the original data and submitted a new run.

But I saved old crash information at:
`/scratch1/BMC/wrfruc/gge/RDASApp/expr/jedi-assim_test/rrfs-data_mpasjedi_2024052700/save/jedi003/jedi.log`

It showed a similar crash.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA 
This time the mpasjedi ran through! I did not know what I had changed. I repeated this experiment multiple times and this is the first time it ran through.

But `adpupa_hofx.nc4 ` now showed a `NaNf `for `oman`

**Comment by guoqing-noaa** [comment]
```
obs_value=268.15
obs_err=1.2
hofx0=262.247
hofx1=NaNf
hofx2=NaNf
ombg=5.902925
```
Don't know why hofx1 and hofx2 get NaN?

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa It looks like the nans make it into the cost function at the start of the minimization: 

```
  0: Initial RHS squared norm = 9.42092
  0: normr0 9.42092
  0:   Residual norm ( 0) = -nan
  0:   Norm reduction ( 0) = 1
  0:
  0:   Quadratic cost function: J   ( 0) = 8.981251009711594
  0:   Quadratic cost function: Jb  ( 0) = 0
  0:   Quadratic cost function: JoJc( 0) = 8.981251009711594
  0:
  0:
  0:  DRPCG Starting Iteration 1
  0: rdots nan      iteration    0
  0: DRPCG end of iteration 1
  0:   Residual norm ( 1) = nan
  0:   Norm reduction ( 1) = nan
  0:
  0:   Quadratic cost function: J   ( 1) = -nan
  0:   Quadratic cost function: Jb  ( 1) = -nan
  0:   Quadratic cost function: JoJc( 1) = -nan
```

Also, I am not sure why mpas-jedi sometimes runs successfully but sometimes crashes in that VertInterp operator. I tried changing the interpolation to nearest-neighbor (basically skipping the interpolation) and now it consistently finishes without the segmentation fault. But I still see the nans like you describe. I am not sure what the problem is here but I can keep investigating.

**Comment by guoqing-noaa** [comment]
Thanks, @SamuelDegelia-NOAA !

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa It appears that the problem was with the localization files created from BUMP. There was a typo in your original `rrfs_mpasjedi_bumploc_2024052621.yaml` file where `bump vunit` was set to `"modelevel"` instead of `"modellevel"`. I corrected this and now mpas-jedi runs successfully without any VertInterp error and produces reasonable oma values.

**Comment by guoqing-noaa** [comment]
Hooray! @SamuelDegelia-NOAA That's a huge help!!! Thanks a lot!

Sorry that my typo caused so many troubles! 
I will prepare this case for all to use today or tomorrow.

**Comment by SamuelDegelia-NOAA** [comment]
Glad to help! I'm surprised that BUMP didn't throw an error and still created the (I'm assuming bad) localization files. It could be worth bringing this up to JCSDA.

**Comment by guoqing-noaa** [comment]
> Glad to help! I'm surprised that BUMP didn't throw an error and still created the (I'm assuming bad) localization files. It could be worth bringing this up to JCSDA.

@SamuelDegelia-NOAA Good idea! Could you help create an issue in the appropriate JCSDA repo?  Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
Will do! I'll submit something tomorrow.

**Comment by guoqing-noaa** [comment]
Thanks, @SamuelDegelia-NOAA 

In your run, what's the OMAN you got?
In my run, I got ombg=5.902975, but oman=5.703303. It looks like there is still something not right.

**Comment by guoqing-noaa** [comment]
![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/2865c810-22f5-401b-8c20-a7d444be8b2e)

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa That is the same increment I saw after debugging yesterday. It is hard to say whether that small increment magnitude is a problem though or not without looking at the background spread. Also, did you run this with all 30 members? I seem to recall when looking through your yaml yesterday that the EnVar was only running with 5 members. It is worth seeing if using all members has an impact there.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA I did try 30 members and the results is quite similar. 

I would expect a much larger increment as seen in the RDASApp ctest mpasjedi case in issue #83 (scroll down to the bottom).

**Comment by SamuelDegelia-NOAA** [comment]
I'll take another look! It is probably worth it to compare the spread between the two test cases just to confirm - I have some scripts around to do that for MPAS.

**Comment by guoqing-noaa** [comment]
> I'll take another look! It is probably worth it to compare the spread between the two test cases just to confirm - I have some scripts around to do that for MPAS.

Great. Thanks, @SamuelDegelia-NOAA 

At the same time, would you mind committing your tools/scripts to the repo, probably under ush/utils? 
@spanNOAA has some Python scripts to plot MPAS results and can commit them to the same subdirectory.

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa The background ensemble spread for this new case appears to be very low and is likely responsible for the small increments compared to #83. See below that compares background spread (T at lev=20) in terms of variance between the two cases: 
<img src="https://github.com/NOAA-EMC/RDASApp/assets/167246325/d829b6e3-5bb9-415e-8414-f7d262a4c382" width="200%" height="200%">

The spread at the observation location is only ~0.05 $K^2$. If we use the EnKF equations as a very simple way to estimate the increment, and assume that the ob is in model space (just assume that the ob is at level 20 for simplicity), then the increment can be estimated as $\Delta x_a = K(y-Hx)$ where $K=\(P^b/(P^b+R))$. Plugging in values from your above figure, $(y-Hx)$ = $5.9$ $K$, $R=1.44$ $K^2$, and $P^b=0.05$ $K^2$. This gives an increment of $\Delta x_a = 0.2$ $K$ which is very close to what you show in the above figure. I would need to compute the covariance between H(x) and model state to get a more realistic estimate, but this is a simple back-of-the-envelope calculation. 

So I think MPAS-JEDI with the new case appears to be working correctly. However, we might want to rethink how the ensemble is created r.e. spread if we want to see larger increments.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks a lot for your great help!
I do not expect the spread to be such small. It comes from GEFS. I guess ,for some reason, our different ensemble forecasts might have used the same ICs. We are examining this.

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa Yeah there might be something wrong with how the members are initialized. If not, then we might want to find some single observation examples in regions where the spread is larger or of a similar magnitude to the ob error.

**Comment by Junjun-NOAA** [comment]
@SamuelDegelia-NOAA Thanks for the ensemble spread you have plotted. Can you share your script with us? We are examining this. Thanks

**Comment by SamuelDegelia-NOAA** [comment]
@Junjun-NOAA The script is on hera at `/home/Samuel.Degelia/mpasjedi_spread.py`. It's written to run in the main mpas-jedi run directory so it looks for the restart files in `Data/ens/${mem}/restart.2024-05-27_00.00.00.nc`. Then it just computes the variance of temperature across the ensemble. Hope that helps!

**Comment by Junjun-NOAA** [comment]
@SamuelDegelia-NOAA Thanks, Sam! We will look at it.

**Comment by guoqing-noaa** [comment]
Thanks @SamuelDegelia-NOAA for sharing the script!

We double checked the ensemble generation process. We did use different GEFS ICs for launch 6h forecasts. But the problem is that we use the same forecast setting to generate those 6h forecasts and ensembles converged very quickly!

I did a quick test using the 6h grib2 files to generate init.nc directly and used them as ensembles. This time, the ensemble spread was improved greatly (see below)! With this test, I will regenerate ensembles using 2700z GEFS grib2 files.

<img width="627" alt="image" src="https://github.com/NOAA-EMC/RDASApp/assets/51679803/a9c909e9-a9c4-4e99-b8b3-0af829c15ae6">

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa That's great! Glad we were able to get this figured out relatively quickly.

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa That's great! Glad we were able to get this figured out relatively quickly.

@SamuelDegelia-NOAA Thanks for your great help! And thanks for the spread-plotting script.

For reference, here is the new spread plot (around 0.44  $K^2$)

![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/b8e5a68f-d5b0-4fe3-98be-05ccdb99fda8)

**Comment by guoqing-noaa** [comment]
This is the conus area spread (NOTE: **color scale changed**)

![image](https://github.com/NOAA-EMC/RDASApp/assets/51679803/daaa3b51-a70b-4565-b589-e2266d802cdc)

**Comment by SamuelDegelia-NOAA** [comment]
That should give us much more reasonable results for the one-ob tests. Thanks for updating the ensemble! 

PS: [An error check for a valid `bump vunit` parameter was just added to MPAS-JEDI.](https://github.com/JCSDA-internal/mpas-jedi/pull/986) They worked very quickly!

**Comment by guoqing-noaa** [comment]
Great! Thanks, @SamuelDegelia-NOAA!

Close this issue.

**Comment by guoqing-noaa** [comment]
level=23, 20240527_00z ensemble spread from 1h MPAS fcst initialized from 35h GEFS forecast

![image](https://github.com/user-attachments/assets/988a29f0-a932-4b9b-9f21-8bbe42064781)
    
    
The associate temperature increment at level 23:
    
![image](https://github.com/user-attachments/assets/79eab15e-faca-43ad-9d4b-38a90b3f62e7)
