### ISSUE TITLE
Centralize test data and reduce unnessary copying

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#93]
All test data are located under a centralized location in each platform and managed by the fix file management team
Personal copies will be avoided in the repository.

```
case ${MACHINE_ID} in
  hera)
    RDAS_DATA=/scratch1/NCEPDEV/fv3-cam/RDAS_DATA
    ;;
  jet)
    RDAS_DATA=/lfs5/BMC/nrtrr/RDAS_DATA
    ;;
  orion|hercules)
    RDAS_DATA=/work/noaa/zrtrr/RDAS_DATA
    ;;
  *)
    echo "platform not supported: ${MACHINE_ID}"
    ;;
esac
```
All the test data are referenced through the fix/ directory under RDASApp and reduce unnecessary copying as much as possible.

Currently, the fix file management team includes:
Shun Liu, Ming Hu
Guoqing Ge, Eric James, Donald Lippi, Samuel Degelia

**Comment by delippi** [comment]
@guoqing-noaa, thanks for getting this started. This has been in the back of my mind to start working on as well. Do we want to update the RDAS/hera.intel module (and other affected files) now since that seems ready to go or wait for the role account to work on all machines and do them all in one PR?

**Comment by guoqing-noaa** [comment]
> @guoqing-noaa, thanks for getting this started. This has been in the back of my mind to start working on as well. Do we want to update the RDAS/hera.intel module (and other affected files) now since that seems ready to go or wait for the role account to work on all machines and do them all in one PR?

Thanks! I can do that using the current configuration while waiting for the `role.rrfs-fv3-cam` account to work on all platforms.
