### ISSUE TITLE
Create mega rdas.x executable

### ISSUE THREAD

**Issue by SamuelDegelia-NOAA** [NOAA-EMC/RDASApp#96]
To be more NCO-compliant, it is desired to create a single `rdas.x` executable instead of using individual executables for each application (i.e., `fv3jedi_letkf.x`, `fv3jedi_var.x`, `fv3jedi_hofx.x`, `fv3jedi_error_covariance_toolbox.x`). I have begun work on this process in #95.

**Comment by guoqing-noaa** [comment]
One question on this: in the future, if there is a need, can we remove some executables from the mega `rdas.x`? 
I don't think we will need fv3jedi and covariance_toolbox, etc in real-time or operational runs.

**Comment by SamuelDegelia-NOAA** [comment]
Right now I am just adding all of the executables that we currently use. But it is very easy to remove them so that should not be a problem in the future.

**Comment by guoqing-noaa** [comment]
> Right now I am just adding all of the executables that we currently use. But it is very easy to remove them so that should not be a problem in the future.

Sounds great. Thanks!

**Comment by TingLei-NOAA** [comment]
To help possible discussions, I attached the gdasapp's issue here https://github.com/NOAA-EMC/GDASApp/issues/1085, which started the "single" jedi executable thing.
